project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "Hands-on Exercise 1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
          - text: "Hands-on Exercise 2"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
          - text: "Hands-on Exercise 3a"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03a.html"
          - text: "Hands-on Exercise 3b"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03b.html"
          - text: "Hands-on Exercise 4a"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04a.html"
          - text: "Hands-on Exercise 4b"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04b.html"
          - text: "Hands-on Exercise 4c"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04c.html"
          - text: "Hands-on Exercise 4d"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04d.html"
          - text: "Hands-on Exercise 5a"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05a.html"
          - text: "Hands-on Exercise 5b"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05b.html"
          - text: "Hands-on Exercise 5c"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05c.html"
          - text: "Hands-on Exercise 5d"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05d.html"
          - text: "Hands-on Exercise 5e"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05e.html"
          - text: "Hands-on Exercise 7a"
            href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07a.html"
          - text: "Hands-on Exercise 7b"
            href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07b.html"
          - text: "Hands-on Exercise 8"
            href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08.html"
          - text: "Hands-on Exercise 9a"
            href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09a.html"
          - text: "Hands-on Exercise 9b"
            href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09b.html"
          - text: "Hands-on Exercise 9c"
            href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09c.html"
          - text: "Hands-on Exercise 10"
            href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex10.html"

      - text: "Take-Home Exercise"
        menu:
          - text: "1: Technical Report"
            href: "Take-Home_Ex/Take-Home_Ex1/Take-Home_Ex01.html"
          - text: "1: Executive Summary"
            href: "Take-Home_Ex/Take-Home_Ex1/Executive_Summary.html"
          - text: "2: Technical Report"
            href: "Take-Home_Ex/Take-Home_Ex2/Take-Home_Ex02.html"
      - text: "Group Project"
        menu:
          - text: "EDA"
            href: "Project/Group_Proj.html"
          - text: "Analytical Computation"
            href: "Project/Analytical_Computation.html"
          - text: "Findings"
            href: "Project/Findings.html"
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: journal
    css: styles.css
    toc: true
    page-layout: full

editor: visual