{
  "hash": "568006afbb865b1fefc1baa70606621f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take-Home Exercise 1\"\nauthor: \"Serene Cheng\"\ndate: \"May 22, 2026\"\ndate-modified: \"last-modified\"\nexecute:\n  eval: true\n  echo: true\n  warning: false\n  freeze: true\n---\n\n# Introduction\n\n## Background\n\nInsurers often manage portfolios whereby the cause of poor profitability and high volatility are not immediately clear. These outcomes may be influenced by a combination of customer profiles, policy, characteristics, claim patterns and it changes over time. This study uses a real-world open-access motor vehicle insurance portfolio dataset and visual analytics libraries in R to explore numerical, categorical, and temporal variables, with the aim of identifying key factors influencing portfolio profitability and volatility.\n\n## The Data\n\nThis study uses a real-world motor vehicle insurance portfolio dataset obtained from a Spanish insurance company that specialises in non-life insurance. The dataset, together with its accompanying cookbook, is publicly available through [Mendeley Data](https://data.mendeley.com/datasets/sw4jmdb2sm/1).\n\n## Objectives\n\nThe objectives of this study are:\n\n-   To apply suitable **univariate visual analytics techniques** to explore the distributions and characteristics of key numerical and categorical variables in the insurance portfolio dataset.\n-   To apply suitable **bivariate visual analytics techniques** to investigate relationships between variables and statistically validate factors influencing the profitability and volatility of the insurance portfolio.\n\n# Getting started\n\n## Loading packages\n\nBegin by loading the following R packages using the p_load() function in the pacman package.\n\n| Package | Description |\n|------------------------------------|------------------------------------|\n| [tidyverse](https://www.tidyverse.org/) | Collection of R packages commonly used for data importing, wrangling, transformation and visualisation. Includes ggplot2, dplyr, tidyr and other core packages. |\n| [ggdist](https://mjskay.github.io/ggdist/) | Used to create distribution-based charts such as half-eye plots, which help show spread, skewness and central tendency |\n| [ggridges](https://cran.r-project.org/web/packages/ggridges/vignettes/introduction.html) | Creates ridgeline plots to compare numerical distributions across categories |\n| [patchwork](https://patchwork.data-imaginist.com/) | Used to combine multiple ggplot charts into one composite figure, such as placing a boxplot above a histogram |\n| [scales](https://scales.r-lib.org/) | Used to format chart labels, such as adding commas to large numbers or displaying percentages |\n| [corrplot](https://cran.r-project.org/web/packages/corrplot/vignettes/corrplot-intro.html) | Used to create correlation matrix visualisations |\n| [rstatix](https://rpkgs.datanovia.com/rstatix/) | Used to run statistical validation tests such as correlation tests, Kruskal-Wallis tests, Wilcoxon tests and chi-square tests |\n| [gganimate](https://gganimate.com/) | Used to create animated ggplot visualisations, allowing temporal trends to be displayed as frame-by-frame animations |\n| [gifski](https://cran.r-project.org/web/packages/gifski/index.html) | Used to render animations as GIF files, working in conjunction with gganimate to produce animated graphics |\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(tidyverse, ggdist, ggridges, patchwork, scales, corrplot, rstatix, gganimate, gifski)\n```\n:::\n\n\n## Data importing\n\nThe motor insurance portfolio data is imported into R using read_delim() function of readr package. read_delim() is used because the data file is semi-colon separated\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmotor_insurance <- read_delim(\"data/Dataset of motor insurance portfolio.csv\", delim = \";\", show_col_types = FALSE)\n```\n:::\n\n\n## Glimpse Data\n\nUse the glimpse() function to get a quick overview of the data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(motor_insurance)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 354,140\nColumns: 47\n$ insured_id                  <dbl> 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, …\n$ year                        <dbl> 2022, 2022, 2023, 2024, 2022, 2023, 2024, …\n$ policy_type                 <chr> \"COMP_E\", \"COMP_E\", \"COMP_E\", \"COMP_E\", \"C…\n$ policy_status               <chr> \"C\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A…\n$ business_type               <chr> \"NB\", \"P\", \"P\", \"P\", \"NB\", \"P\", \"P\", \"NB\",…\n$ payment_frequency           <chr> \"A\", \"A\", \"A\", \"A\", \"S\", \"S\", \"S\", \"A\", \"A…\n$ bonus_score                 <chr> \"G\", \"G\", \"G\", \"G\", \"G\", \"G\", \"G\", \"G\", \"G…\n$ driver_age                  <dbl> 48, 43, 44, 45, 45, 46, 47, 32, 33, 34, 39…\n$ vehicle_age                 <dbl> 22, 24, 25, 26, 26, 27, 28, 12, 13, 14, 20…\n$ age_driving_licence         <dbl> 26, 19, 19, 18, 19, 19, 19, 19, 19, 19, 19…\n$ fuel_type                   <chr> \"G\", \"D\", \"D\", \"D\", \"D\", \"D\", \"D\", \"D\", \"D…\n$ vehicle_value               <dbl> 149511.44, 65065.12, 65065.12, 65065.12, 5…\n$ seats                       <dbl> 4, 8, 8, 8, 7, 7, 7, 5, 5, 5, 5, 5, 5, 5, …\n$ power_to_weight_ratio       <dbl> 3.92, 10.15, 10.15, 10.15, 9.19, 9.19, 9.1…\n$ vehicle_brand               <chr> \"PORSCHE\", \"MERCEDES\", \"MERCEDES\", \"MERCED…\n$ municipality_type           <chr> \"I\", \"I\", \"I\", \"I\", \"I\", \"I\", \"I\", \"I\", \"I…\n$ circulation_area            <chr> \"U\", \"U\", \"U\", \"U\", \"R\", \"R\", \"R\", \"R\", \"R…\n$ total_premium               <dbl> 279.5576, 546.6234, 548.7526, 584.6324, 68…\n$ liability_premium           <dbl> 30.60232, 114.33336, 110.66689, 122.09253,…\n$ property_damage_premium     <dbl> 121.9127, 303.1060, 304.9560, 305.2251, 35…\n$ theft_premium               <dbl> 112.361489, 80.784824, 83.521384, 107.8868…\n$ fire_premium                <dbl> 3.832441, 7.826861, 6.151465, 5.842892, 7.…\n$ glass_premium               <dbl> 8.305788, 30.091751, 32.861626, 31.101584,…\n$ legal_protection_premium    <dbl> 2.043622, 7.812747, 7.655637, 10.084173, 6…\n$ occupants_premium           <dbl> 0.4992053, 2.6679084, 2.9395659, 2.3992827…\n$ total_claims                <dbl> 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, …\n$ liability_claims            <dbl> 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ liability_property_claims   <dbl> 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ liability_injury_claims     <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ property_claims             <dbl> 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, …\n$ theft_claims                <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ fire_claims                 <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ glass_claims                <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ legal_protection_claims     <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ occupants_claims            <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ total_incurred              <dbl> 0.000, 0.000, 233.013, 2586.361, 0.000, 0.…\n$ liability_incurred          <dbl> 0.000, 0.000, 233.013, 1035.000, 0.000, 0.…\n$ liability_property_incurred <dbl> 0.000, 0.000, 233.013, 1035.000, 0.000, 0.…\n$ liability_injury_incurred   <dbl> 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, …\n$ property_incurred           <dbl> 0.000, 0.000, 0.000, 1551.361, 0.000, 0.00…\n$ theft_incurred              <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ fire_incurred               <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ glass_incurred              <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ legal_protection_incurred   <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ occupants_incurred          <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ total_exposure              <dbl> 0.09863014, 1.00000000, 1.00000000, 1.0000…\n$ liability_exposure          <dbl> 0.09863014, 1.00000000, 1.00000000, 1.0000…\n```\n\n\n:::\n:::\n\n\n::: {.callout-note title=\"Insights\"}\nThe raw dataset has **354,140 rows** and **many policy, vehicle, premium, claim and exposure variables**.\n:::\n\n## Data Wrangling\n\n### 1. Check for duplicates\n\nNo record found for duplicated rows\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(duplicated(motor_insurance))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\nNo records found for duplicated policy-year records.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmotor_insurance %>%\n  count(insured_id, year) %>%\n  filter(n > 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 0 × 3\n# ℹ 3 variables: insured_id <dbl>, year <dbl>, n <int>\n```\n\n\n:::\n:::\n\n\n### 2. Check for missing values by column\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmotor_insurance %>%\n  summarise(across(everything(), ~ sum(is.na(.)))) %>%\n  pivot_longer(\n    cols = everything(),\n    names_to = \"variable\",\n    values_to = \"missing_count\"\n  ) %>%\n  filter(missing_count > 0) %>%\n  arrange(desc(missing_count))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 2\n  variable            missing_count\n  <chr>                       <int>\n1 fuel_type                    1287\n2 vehicle_value                 513\n3 vehicle_age                     2\n4 age_driving_licence             2\n```\n\n\n:::\n:::\n\n\nThe largest missing column is fuel_type with 1,287 missing rows followed by vehicle_value, vehicle_age and age_driving_licence. We will first do variable selection then drop the rows with missing values.\n\n### 3. Variable Selection\n\nThe original dataset contains 42 columns covering policy details, driver and vehicle characteristics, premium components, claim counts, incurred losses, and exposure. To keep the visual analysis focused, only variables that are relevant to overall portfolio profitability, volatility and potential loss drivers are retained.\n\nDetailed coverage-level premium, claim, and incurred loss variables were excluded from the main analysis because the focus is on overall portfolio-level profitability and volatility.\n\n| Variables | Retain Reason |\n|------------------------------------|------------------------------------|\n| year | Retained as temporal variable to examine changes across years |\n| policy_status | To compare active and cancelled policies |\n| policy_type | Different coverage may have different premium and claim behavior |\n| business_type | To compare new and existing portfolio policies |\n| bonus_score | Reflect policyholder's past claims experience and may influence future claim risk |\n| driver_age | Key driver characteristics that may affect claim frequency and risk behavior |\n| vehicle_age | Older vehicle may have different claim patterns, repair needs or loss severity |\n| age_driving_licence | Kept to derive driving_experience which is more meaningful for analysis |\n| fuel_type | To explore whether diesel and gasoline vehicles show different claim/profitability patterns |\n| vehicle_value | Vehicle value can influence claim severity and potential incurred losses |\n| vehicle_brand | For segment-level analysis, compare top vehicle brands by loss ratio or claim frequency |\n| circulation_area | To compare urban and rural driving environments which may influence claim exposure and frequency |\n| municipality_type | Retained as geographic indicator to examine whether different areas diff in risk and profitability |\n| total_premium | For measuring revenue and deriving loss ratio and underwriting profit |\n| total_claims | For measuring claim frequency and portfolio volatility |\n| total_incurred | For measuring total claim cost and portfolio volatility |\n| total_exposure | For normalising claims by time-on-risk to allow fair comparison across policies |\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmotor_insurance_selected <- motor_insurance %>%\n  select(\n    year,\n    policy_status,\n    policy_type,\n    business_type,\n    bonus_score,\n    driver_age,\n    vehicle_age,\n    age_driving_licence,\n    fuel_type,\n    vehicle_value,\n    vehicle_brand,\n    circulation_area,\n    municipality_type,\n    total_premium,\n    total_claims,\n    total_incurred,\n    total_exposure\n  )\n```\n:::\n\n\n### 4. Dropping rows with missing value\n\nSince the overall number of affected rows is small relative to the dataset size, rows with missing values were removed for completeness before visual analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmotor_insurance_clean <- motor_insurance_selected %>%\n  drop_na()\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(motor_insurance) - nrow(motor_insurance_clean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1802\n```\n\n\n:::\n:::\n\n\nAfter applying `drop_na()`, a total of 1,802 rows were removed. 1,802 / 354,140 = 0.51% which is considered as not significant\n\n### 5. Variable Transformation\n\n#### i. Creating a new variable from existing variables\n\nAfter variable selection, new analytical variables were derived to investigate the portfolio's profitability and volatility. `driving_experience` was created by subtracting `age_driving_licence` from `driver_age` to approximate the number of years the driver has held a licence.\n\nSeveral profitability-related measures were also derived including: - `loss_ratio` (total_incurred/total_premium): Measures claims incurred relative to premium collected. Used as a profitability indicator - `underwriting_profit` (total_premium - total_incurred): Measures simplified underwriting profit before expenses, commissions, reinsurance, and investment income - `claim_frequency` (total_claims/total_exposure): Measures how often claims occur after adjusting for time-on-risk. Used to assess claim activity and volatility - `claim_severity` (total_incurred/total_claims): Measures the average incurred cost per claim. Used to assess the size or severity of claims.\n\nThese variables are created in accordance with actuarial/industry standards\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmotor_insurance_final <- motor_insurance_clean %>%\n  mutate(\n    driving_experience = driver_age - age_driving_licence,\n    loss_ratio = total_incurred / total_premium,\n    claim_frequency = total_claims / total_exposure,\n    claim_severity = if_else(total_claims > 0, total_incurred / total_claims, NA_real_),\n    underwriting_profit = total_premium - total_incurred\n  ) %>%\n  select(-age_driving_licence)\n```\n:::\n\n\n#### ii. Changing data type\n\nAfter deriving the new variables, the data types were reviewed to ensure that each variable is treated appropriately for visual analysis. Variables such as `policy_status`, `policy_type`, `business_type`, `bonus_score`, `fuel_type`, `vehicle_brand`, `circulation_area`, and `municipality_type` were converted from character variables into factors because they represent categorical groups rather than continuous values.\n\nNumerical variables such as `driver_age`, `vehicle_age`, `vehicle_value`, `total_premium`, `total_claims`, `total_incurred`, `total_exposure`, `loss_ratio`, `claim_frequency`, `claim_severity`, and `underwriting_profit` were kept as numeric variables for distribution analysis, correlation analysis, and bivariate visualisation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmotor_insurance_final <- motor_insurance_final %>%\n  mutate(\n    policy_status = as.factor(policy_status),\n    policy_type = as.factor(policy_type),\n    business_type = as.factor(business_type),\n    bonus_score = as.factor(bonus_score),\n    fuel_type = as.factor(fuel_type),\n    vehicle_brand = as.factor(vehicle_brand),\n    circulation_area = as.factor(circulation_area),\n    municipality_type = as.factor(municipality_type)\n  )\n```\n:::\n\n\n#### iii. Recoding categorical variables\n\nSome categorical variables were originally coded using short labels. These were recoded into more descriptive labels to improve the readability of the visualisations.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmotor_insurance_final <- motor_insurance_final %>%\n  mutate(\n    policy_status = recode(policy_status,\n                           \"A\" = \"Active\",\n                           \"C\" = \"Cancelled\"),\n    business_type = recode(business_type,\n                           \"NB\" = \"New Business\",\n                           \"P\" = \"Portfolio\"),\n    bonus_score = recode(bonus_score,\n                         \"G\" = \"Good\",\n                         \"N\" = \"Neutral\",\n                         \"B\" = \"Bad\"),\n    fuel_type = recode(fuel_type,\n                       \"D\" = \"Diesel\",\n                       \"G\" = \"Gasoline\"),\n    circulation_area = recode(circulation_area,\n                              \"U\" = \"Urban\",\n                              \"R\" = \"Rural\"),\n    municipality_type = recode(municipality_type,\n                               \"I\" = \"Inland\",\n                               \"C\" = \"Coastal\",\n                               \"IS\" = \"Islands\")\n  )\n```\n:::\n\n\n### 6. Final Variables Selected for Visual Analysis\n\n| Analysis Area | Variables Used |\n|------------------------------------|------------------------------------|\n| Policy/Policyholder profile | `year`, `policy_status`, `policy_type`, `business_type`, `bonus_score`, `driver_age`, `age_driving_licence` |\n| Vehicle profile | `vehicle_age`, `fuel_type`, `vehicle_value`, `vehicle_brand` |\n| Geographic / driving environment | `circulation_area`, `municipality_type` |\n| Premium and exposure | `total_premium`, `total_exposure` |\n| Claims and incurred losses | `total_claims`, `total_incurred` |\n| Derived profitability variables | `loss_ratio`, `underwriting_profit` |\n| Derived volatility variables | `claim_frequency`, `claim_severity` |\n| Derived driver variable | `driving_experience` |\n\n# Univariate Visual Analytics\n\nNot all retained variables were visualised individually in the univariate analysis. Some variables were retained because they were required to derive analytical measures such as `loss_ratio`, \\``claim_frequency`, `claim_severity`, and `underwriting_profit`, while others were kept as supporting variables for bivariate analysis. The univariate analysis focuses on variables most relevant to portfolio composition, driver and vehicle profile, profitability, and claim volatility\n\n## 1. Policy/Policyholder profile\n\n### 1.1 Policy Type\n\n::: panel-tabset\n## Plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Main count table\npolicy_type_summary <- motor_insurance_final %>%\n  count(policy_type) %>%\n  mutate(\n    percentage = n / sum(n) * 100,\n    label = paste0(scales::comma(n), \"\\n(\", round(percentage, 1), \"%)\")\n  )\n\n# Reorder factor levels for plotting\npolicy_type_summary <- policy_type_summary %>%\n  mutate(\n    policy_type = factor(\n      policy_type,\n      levels = c(\"TP\", \"COMP_N\", \"TPG\", \"COMP_E\", \"CC\")\n    )\n  )\n\n# Description table for annotation on the right\npolicy_desc <- tibble(\n  policy_type = factor(\n    c(\"CC\", \"COMP_E\", \"TPG\", \"COMP_N\", \"TP\"),\n    levels = levels(policy_type_summary$policy_type)\n  ),\n  desc = c(\n    \"CC: Third-party liability with two or more additional coverages\",\n    \"COMP_E: Comprehensive with excess\",\n    \"TPG: Third-party liability with glass coverage\",\n    \"COMP_N: Comprehensive without excess\",\n    \"TP: Basic third-party liability only\"\n  ),\n  xpos = c(260000, 260000, 260000, 260000, 260000)\n)\n\nggplot(policy_type_summary, aes(x = policy_type, y = n, fill = policy_type)) +\n  geom_col(colour = \"white\") +\n  geom_text(\n    aes(label = label),\n    hjust = -0.1,\n    size = 3.5\n  ) +\n  geom_text(\n    data = policy_desc,\n    aes(x = policy_type, y = xpos, label = desc),\n    inherit.aes = FALSE,\n    hjust = 0,\n    size = 3.2,\n    colour = \"black\"\n  ) +\n  coord_flip(clip = \"off\") +\n  scale_y_continuous(\n    labels = scales::comma,\n    expand = expansion(mult = c(0, 0.55))\n  ) +\n  scale_fill_brewer(palette = \"Set2\") +\n  labs(\n    title = \"Distribution of Policy Type\",\n    subtitle = \"Shows the coverage mix of the insurance portfolio\",\n    x = \"Policy Type\",\n    y = \"Number of Policies\"\n  ) +\n  theme_minimal() +\n  theme(\n    legend.position = \"none\",\n    plot.margin = margin(t = 10, r = 180, b = 10, l = 10)\n  )\n```\n:::\n\n:::\n\n::: {.callout-note title=\"Insights\"}\n-   The portfolio is dominated by **CC** policies. **CC** accounts for **204,317 policies (58.0%)** of the portfolio.\n\n-   Most policies include third-party liability with two or more additional coverages.\n\n-   **COMP_E** is the second largest group with **90,320 policies (25.6%)**.\n\n-   **TPG** accounts for **35,988 policies (10.2%)**.\n\n-   **COMP_N** and **TP** make up much smaller shares at **4.5%** and **1.6%** respectively.\n\n-   Overall, portfolio is more concentrated in broader coverage types rather than basic third-party-only policies.\n:::\n\n### 1.2 Bonus Score\n\n::: panel-tabset\n## Plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmotor_insurance_final %>%\n  filter(!is.na(bonus_score)) %>%\n  count(bonus_score) %>%\n  mutate(\n    percentage = n / sum(n) * 100,\n    bonus_score = factor(\n      bonus_score,\n      levels = c(\"Good\", \"Neutral\", \"Bad\")\n    ),\n    label = paste0(scales::comma(n), \"\\n(\", round(percentage, 1), \"%)\")\n  ) %>%\n  ggplot(aes(x = bonus_score, y = n, fill = bonus_score)) +\n  geom_col(colour = \"white\") +\n  geom_text(\n    aes(label = label),\n    vjust = -0.4,\n    size = 3.5\n  ) +\n  scale_y_continuous(\n    labels = scales::comma,\n    expand = expansion(mult = c(0, 0.25))\n  ) +\n  scale_fill_brewer(palette = \"Pastel1\") +\n  labs(\n    title = \"Distribution of Bonus Score\",\n    subtitle = \"Shows the past claims profile of policyholders\",\n    x = \"Bonus Score\",\n    y = \"Number of Policies\"\n  ) +\n  theme_minimal() +\n  theme(\n    legend.position = \"none\",\n    plot.margin = margin(t = 20, r = 10, b = 10, l = 10)\n  )\n```\n:::\n\n:::\n\n::: {.callout-note title=\"Insights\"}\n-   The portfolio is heavily dominated by policyholders with a **Good** bonus score.\n-   **Good** bonus score accounts for **339,836 policies (96.5%)**.\n-   This suggests that most policyholders have a favourable past claims history.\n-   **Neutral** and **Bad** bonus score accounts for **7,809 policies (2.2%)** and **4,693 policies (1.3%)** respectively\n-   Although the Neutral and Bad groups are small, they can still be explored further in bivariate analysis to see whether they are linked to higher `claim_frequency` or poorer `loss_ratio`.\n:::\n\n### 1.3 Driver Age\n\n::: panel-tabset\n## Plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Summary statistics\nmean_age <- round(mean(motor_insurance_final$driver_age, na.rm = TRUE), 0)\nmedian_age <- round(median(motor_insurance_final$driver_age, na.rm = TRUE), 0)\nsd_age <- round(sd(motor_insurance_final$driver_age, na.rm = TRUE), 1)\n\n# Boxplot\ndriver_age_box <- ggplot(motor_insurance_final, aes(x = driver_age, y = \"\")) +\n  geom_boxplot(\n    fill = \"grey80\",\n    colour = \"grey30\",\n    outlier.colour = \"grey50\",\n    outlier.alpha = 0.4\n  ) +\n  stat_summary(\n    fun = mean,\n    geom = \"point\",\n    colour = \"coral\",\n    size = 3\n  ) +\n  scale_x_continuous(\n    breaks = seq(20, 85, by = 5)\n  ) +\n  coord_cartesian(xlim = c(20, 85)) +\n  labs(\n    title = \"Distribution of Driver Age\",\n    x = NULL,\n    y = NULL\n  ) +\n  theme_minimal() +\n  theme(\n    axis.text.y = element_blank(),\n    axis.ticks.y = element_blank(),\n    panel.grid.major.y = element_blank()\n  )\n\n# Histogram\ndriver_age_hist <- ggplot(motor_insurance_final, aes(x = driver_age)) +\n  geom_histogram(\n    bins = 20,\n    fill = \"steelblue\",\n    colour = \"white\"\n  ) +\n  geom_vline(\n    xintercept = mean_age,\n    colour = \"coral\",\n    linetype = \"dashed\",\n    linewidth = 0.8\n  ) +\n  geom_vline(\n    xintercept = median_age,\n    colour = \"blue\",\n    linetype = \"dashed\",\n    linewidth = 0.8\n  ) +\n  annotate(\n    \"text\",\n    x = median_age - 6,\n    y = 39500,\n    label = paste0(\"Median = \", median_age),\n    colour = \"blue\",\n    size = 3.5\n  ) +\n  annotate(\n    \"text\",\n    x = mean_age + 6,\n    y = 43000,\n    label = paste0(\"Mean = \", mean_age),\n    colour = \"coral\",\n    size = 3.5\n  ) +\n  annotate(\n    \"text\",\n    x = 72,\n    y = 43000,\n    label = paste0(\"SD = \", sd_age),\n    colour = \"grey30\",\n    size = 3.5\n  ) +\n  scale_x_continuous(\n    breaks = seq(20, 85, by = 5)\n  ) +\n  coord_cartesian(xlim = c(20, 85)) +\n  labs(\n    x = \"Driver Age\",\n    y = \"Number of Policies\"\n  ) +\n  theme_minimal()\n\n# Combine boxplot and histogram\ndriver_age_box / driver_age_hist +\n  plot_layout(heights = c(1, 3))\n```\n:::\n\n:::\n\n::: {.callout-note title=\"Insights\"}\n-   Most insured drivers are concentrated between **35 and 65 years old**, with the highest number of policies around the **40 to 45** age range.\n\n-   This suggests that the portfolio is mainly made up of **middle-aged drivers**, while very young and very old drivers form a smaller share.\n\n-   The distribution is **slightly right-skewed**, with policy counts gradually declining as driver age increases beyond the mid-40s.\n:::\n\n## 2. Vehicle Profile\n\n### 2.1 Vehicle Value\n\nWe can see from the initial boxplot distribution that vehicle value is highly right-skewed, with most insured vehicles concentrated at lower values and a small number of very high-value vehicles appearing as outliers. This suggests that the portfolio mainly consists of lower to mid-value vehicles, while a smaller group of luxury or high-value vehicles may have greater potential claim severity.\n\n::: panel-tabset\n## Plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Summary statistics\nmean_vehicle_value <- round(mean(motor_insurance_final$vehicle_value, na.rm = TRUE), 0)\nmedian_vehicle_value <- round(median(motor_insurance_final$vehicle_value, na.rm = TRUE), 0)\nsd_vehicle_value <- round(sd(motor_insurance_final$vehicle_value, na.rm = TRUE), 0)\n\n# Boxplot\nvehicle_value_box <- ggplot(motor_insurance_final, aes(x = vehicle_value, y = \"\")) +\n  geom_boxplot(\n    fill = \"grey80\",\n    colour = \"grey30\",\n    outlier.colour = \"grey50\",\n    outlier.alpha = 0.35\n  ) +\n  stat_summary(\n    fun = mean,\n    geom = \"point\",\n    colour = \"black\",\n    size = 3\n  ) +\n  coord_cartesian(xlim = c(0, 100000)) +\n  scale_x_continuous(\n    labels = scales::comma,\n    breaks = seq(0, 100000, by = 25000)\n  ) +\n  labs(\n    title = \"Distribution of Vehicle Value\",\n    x = NULL,\n    y = NULL\n  ) +\n  theme_minimal() +\n  theme(\n    axis.text.y = element_blank(),\n    axis.ticks.y = element_blank(),\n    panel.grid.major.y = element_blank()\n  )\n\n# Histogram\nvehicle_value_hist <- ggplot(motor_insurance_final, aes(x = vehicle_value)) +\n  geom_histogram(\n    bins = 50,\n    fill = \"coral\",\n    colour = \"white\"\n  ) +\n  geom_vline(\n    xintercept = median_vehicle_value,\n    colour = \"blue\",\n    linetype = \"dashed\",\n    linewidth = 0.8\n  ) +\n  geom_vline(\n    xintercept = mean_vehicle_value,\n    colour = \"black\",\n    linetype = \"dashed\",\n    linewidth = 0.8\n  ) +\n  annotate(\n    \"text\",\n    x = median_vehicle_value - 12000,\n    y = 84000,\n    label = paste0(\"Median = \", scales::comma(median_vehicle_value)),\n    colour = \"blue\",\n    size = 3.5\n  ) +\n  annotate(\n    \"text\",\n    x = mean_vehicle_value + 11000,\n    y = 99000,\n    label = paste0(\"Mean = \", scales::comma(mean_vehicle_value)),\n    colour = \"black\",\n    size = 3.5\n  ) +\n  annotate(\n    \"text\",\n    x = 75000,\n    y = 99000,\n    label = paste0(\"SD = \", scales::comma(sd_vehicle_value)),\n    colour = \"grey30\",\n    size = 3.5\n  ) +\n  coord_cartesian(xlim = c(0, 100000)) +\n  scale_x_continuous(\n    labels = scales::comma,\n    breaks = seq(0, 100000, by = 25000)\n  ) +\n  scale_y_continuous(labels = scales::comma) +\n  labs(\n    subtitle = \"X-axis is zoomed to show the main concentration of vehicle values\",\n    x = \"Vehicle Value\",\n    y = \"Number of Policies\"\n  ) +\n  theme_minimal()\n\n# Combine boxplot and histogram\nvehicle_value_box / vehicle_value_hist +\n  plot_layout(heights = c(1, 3))\n```\n:::\n\n:::\n\n::: {.callout-note title=\"Insights\"}\n-   Vehicle value is **right-skewed**, with most insured vehicles concentrated in the lower to mid-value range.\n-   The **median vehicle value is 24,687**, while the **mean is higher at 26,937**, suggesting that high-value vehicles pull the average upward.\n-   Most policies are clustered below around **35,000**, but the boxplot shows several high-value outliers, which may be linked to greater potential claim severity.\n:::\n\n### 2.2 Vehicle Age\n\n::: panel-tabset\n## Plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Summary statistics\nmean_vehicle_age <- round(mean(motor_insurance_final$vehicle_age, na.rm = TRUE), 0)\nmedian_vehicle_age <- round(median(motor_insurance_final$vehicle_age, na.rm = TRUE), 0)\nsd_vehicle_age <- round(sd(motor_insurance_final$vehicle_age, na.rm = TRUE), 1)\n\n# Boxplot\nvehicle_age_box <- ggplot(motor_insurance_final, aes(x = vehicle_age, y = \"\")) +\n  geom_boxplot(\n    fill = \"grey80\",\n    colour = \"grey30\",\n    outlier.colour = \"grey50\",\n    outlier.alpha = 0.35\n  ) +\n  stat_summary(\n    fun = mean,\n    geom = \"point\",\n    colour = \"coral\",\n    size = 3\n  ) +\n  scale_x_continuous(\n    breaks = seq(0, 70, by = 5)\n  ) +\n  coord_cartesian(xlim = c(0, 70)) +\n  labs(\n    title = \"Distribution of Vehicle Age\",\n    x = NULL,\n    y = NULL\n  ) +\n  theme_minimal() +\n  theme(\n    axis.text.y = element_blank(),\n    axis.ticks.y = element_blank(),\n    panel.grid.major.y = element_blank()\n  )\n\n# Density plot\nvehicle_age_density <- ggplot(motor_insurance_final, aes(x = vehicle_age)) +\n  geom_density(\n    fill = \"darkseagreen\",\n    alpha = 0.6,\n    colour = \"darkgreen\"\n  ) +\n  geom_vline(\n    xintercept = median_vehicle_age,\n    colour = \"blue\",\n    linetype = \"dashed\",\n    linewidth = 0.8\n  ) +\n  geom_vline(\n    xintercept = mean_vehicle_age,\n    colour = \"coral\",\n    linetype = \"dashed\",\n    linewidth = 0.8\n  ) +\n  annotate(\n    \"text\",\n    x = median_vehicle_age - 8,\n    y = 0.029,\n    label = paste0(\"Median = \", median_vehicle_age),\n    colour = \"blue\",\n    size = 3.5\n  ) +\n  annotate(\n    \"text\",\n    x = mean_vehicle_age + 8,\n    y = 0.031,\n    label = paste0(\"Mean = \", mean_vehicle_age),\n    colour = \"coral\",\n    size = 3.5\n  ) +\n  annotate(\n    \"text\",\n    x = 52,\n    y = 0.031,\n    label = paste0(\"SD = \", sd_vehicle_age),\n    colour = \"grey30\",\n    size = 3.5\n  ) +\n  scale_x_continuous(\n    breaks = seq(0, 70, by = 5)\n  ) +\n  coord_cartesian(xlim = c(0, 70)) +\n  labs(\n    subtitle = \"Smoothed distribution showing the concentration of insured vehicle ages\",\n    x = \"Vehicle Age\",\n    y = \"Density\"\n  ) +\n  theme_minimal()\n\n# Combine boxplot and density plot\nvehicle_age_box / vehicle_age_density +\n  plot_layout(heights = c(1, 3))\n```\n:::\n\n:::\n\n::: {.callout-note title=\"Insights\"}\n-   Vehicle age is mainly concentrated around **15 to 35 years**, suggesting that the portfolio mostly contains mature vehicles rather than very new vehicles.\n-   The **median vehicle age is 25** and the **mean is 26**, so the distribution is fairly balanced with only slight right-skewness.\n-   There is a smaller second peak around **35 to 40 years**, indicating another group of older insured vehicles.\n-   The boxplot shows a few older vehicle outliers above **60 years**, but these make up only a small portion of the portfolio.\n:::\n\n### 2.3 Vehicle Brand\n\nVehicle brand is visualised using a bar chart of the top 10 brands by policy count. Since there may be many vehicle brands, only the most common brands are shown individually, while the remaining brands are grouped under **Others** to keep the chart readable.\n\n::: panel-tabset\n## Plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-23-1.png){width=960}\n:::\n:::\n\n\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Identify top 10 vehicle brands by policy count\ntop_vehicle_brands <- motor_insurance_final %>%\n  filter(!is.na(vehicle_brand)) %>%\n  count(vehicle_brand, sort = TRUE) %>%\n  slice_head(n = 10) %>%\n  pull(vehicle_brand)\n\n# Prepare vehicle brand summary\nvehicle_brand_summary <- motor_insurance_final %>%\n  filter(!is.na(vehicle_brand)) %>%\n  mutate(\n    vehicle_brand_grouped = if_else(\n      vehicle_brand %in% top_vehicle_brands,\n      as.character(vehicle_brand),\n      \"Others\"\n    )\n  ) %>%\n  count(vehicle_brand_grouped, name = \"n\") %>%\n  mutate(\n    percentage = n / sum(n),\n    label = paste0(scales::comma(n), \"\\n\", scales::percent(percentage, accuracy = 0.1)),\n    vehicle_brand_grouped = fct_reorder(vehicle_brand_grouped, n)\n  )\n\n# Plot\nvehicle_brand_summary %>%\n  ggplot(aes(\n    x = vehicle_brand_grouped,\n    y = n,\n    fill = vehicle_brand_grouped\n  )) +\n  geom_col(colour = \"white\") +\n  geom_text(\n    aes(label = label),\n    hjust = -0.1,\n    size = 3.3\n  ) +\n  coord_flip() +\n  scale_y_continuous(\n    labels = scales::comma,\n    expand = expansion(mult = c(0, 0.25))\n  ) +\n  scale_fill_brewer(palette = \"Set3\") +\n  labs(\n    title = \"Distribution of Vehicle Brand\",\n    subtitle = \"Top 10 vehicle brands by policy count, with remaining brands grouped as Others\",\n    x = \"Vehicle Brand\",\n    y = \"Number of Policies\"\n  ) +\n  theme_minimal() +\n  theme(\n    legend.position = \"none\"\n  )\n```\n:::\n\n:::\n\n::: {.callout-note title=\"Insights\"}\n-   Vehicle brand is relatively diverse, with the **Others** group forming the largest share at **27.6%** meaning many smaller brands exist outside the top 10\n\n-   Among individual brands, **Renault** has the highest policy count at **34,311 policies (9.7%)**, followed by **Citroen** at **32,476 policies (9.2%)** and **Peugeot** at **29,519 policies (8.4%)**\n\n-   Since no single vehicle brand dominates the portfolio, vehicle brand may be more useful for grouped or top-brand bivariate analysis rather than analysing every brand individually\n:::\n\n## 3. Geographic/Driving Environment\n\n### 3.1 Circulation Area\n\nA donut chart was used for circulation_area because it is a binary categorical variable with only two groups, making it easy to compare the portfolio share of urban and rural policies.\n\n::: panel-tabset\n## Plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncirculation_summary <- motor_insurance_final %>%\n  filter(!is.na(circulation_area)) %>%\n  count(circulation_area) %>%\n  mutate(\n    percentage = n / sum(n) * 100,\n    label = paste0(circulation_area, \"\\n\", scales::comma(n), \"\\n(\", round(percentage, 1), \"%)\")\n  )\n\nggplot(circulation_summary, aes(x = 2, y = n, fill = circulation_area)) +\n  geom_col(width = 1, colour = \"white\") +\n  coord_polar(theta = \"y\") +\n  xlim(0.5, 2.5) +\n  geom_text(\n    aes(label = label),\n    position = position_stack(vjust = 0.5),\n    size = 3.5\n  ) +\n  scale_fill_brewer(palette = \"Set2\") +\n  labs(\n    title = \"Distribution of Circulation Area\",\n    subtitle = \"Donut chart showing the urban and rural composition of the insured portfolio\",\n    fill = \"Circulation Area\"\n  ) +\n  theme_void() +\n  theme(\n    plot.title = element_text(hjust = 0),\n    plot.subtitle = element_text(hjust = 0),\n    legend.position = \"none\"\n  )\n```\n:::\n\n:::\n\n::: {.callout-note title=\"Insights\"}\n-   The portfolio is fairly balanced between **Urban** and **Rural** circulation areas.\n\n-   **Urban** policies form a slightly larger share at **189,477 policies (53.8%)**.\n\n-   **Rural** policies account for **162,861 policies (46.2%)**.\n\n-   Insurer has exposure across both driving environments.\n\n-   Since urban areas may have higher traffic density, this variable can be explored further in bivariate analysis with `claim_frequency`, `claim_severity`, or `loss_ratio`.\n:::\n\n## 4. Derived profitability variables\n\n### 4.1 Loss Ratio and Loss Ratio Group\n\nThe histogram shows that loss_ratio is highly concentrated near zero, mainly because many policies have no incurred claims. There are also a small number of extreme high loss ratio values, where incurred claims are much larger than premiums. This makes the raw numerical distribution difficult to interpret using a standard histogram.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nloss_ratio_data <- motor_insurance_final %>%\n  filter(is.finite(loss_ratio))\n\nggplot(loss_ratio_data, aes(x = loss_ratio)) +\n  geom_histogram(\n    binwidth = 0.1,\n    fill = \"mediumpurple\",\n    colour = \"white\"\n  ) +\n  coord_cartesian(xlim = c(0, 5)) +\n  scale_x_continuous(\n    breaks = seq(0, 5, by = 0.5)\n  ) +\n  scale_y_continuous(labels = scales::comma) +\n  labs(\n    title = \"Distribution of Loss Ratio\",\n    x = \"Loss Ratio\",\n    y = \"Number of Policies\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\nData transformation is performed to change loss ratio into categorical variable\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmotor_insurance_final <- motor_insurance_final %>%\n  mutate(\n    loss_ratio_group = case_when(\n      loss_ratio == 0 ~ \"No Loss\",\n      loss_ratio > 0 & loss_ratio <= 1 ~ \"Profitable / Acceptable\",\n      loss_ratio > 1 ~ \"Loss-making\"\n    )\n  )\n```\n:::\n\n\n::: panel-tabset\n## Plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmotor_insurance_final %>%\n  filter(!is.na(loss_ratio_group)) %>%\n  count(loss_ratio_group) %>%\n  mutate(\n    percentage = n / sum(n) * 100,\n    loss_ratio_group = factor(\n      loss_ratio_group,\n      levels = c(\"No Loss\", \"Profitable / Acceptable\", \"Loss-making\")\n    ),\n    label = paste0(scales::comma(n), \"\\n(\", round(percentage, 1), \"%)\")\n  ) %>%\n  ggplot(aes(x = loss_ratio_group, y = n)) +\n  geom_col(fill = \"mediumpurple\", colour = \"white\") +\n  geom_text(\n    aes(label = label),\n    vjust = -0.4,\n    size = 3.5\n  ) +\n  scale_y_continuous(\n    labels = scales::comma,\n    expand = expansion(mult = c(0, 0.25))\n  ) +\n  coord_cartesian(clip = \"off\") +\n  labs(\n    title = \"Distribution of Loss Ratio Groups\",\n    subtitle = \"Loss ratio was grouped to improve interpretability of the profitability profile\",\n    x = \"Loss Ratio Group\",\n    y = \"Number of Policies\"\n  ) +\n  theme_minimal() +\n  theme(\n    plot.margin = margin(t = 20, r = 10, b = 10, l = 10)\n  )\n```\n:::\n\n:::\n\n::: {.callout-note title=\"Insights\"}\n-   Most policies fall under the **No Loss** group, meaning they did not record any incurred claims during the exposure period.\n\n-   This is expected in insurance portfolios, where many policyholders do not make claims within a given year.\n\n-   A smaller proportion falls under **Profitable / Acceptable**, where incurred claims are positive but do not exceed premium collected.\n\n-   The **Loss-making** group is smaller but important, as these policies have incurred claims greater than premium and may drive profitability pressure in the portfolio.\n:::\n\n## 5. Derived volatility variables\n\n### 5.1 Claims Frequency and Claim Frequency Group\n\n`claim_frequency` is also zero-heavy as shown in the histogram below, because most policies have no claims\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclaim_frequency_data <- motor_insurance_final %>%\n  filter(is.finite(claim_frequency))\n\nggplot(claim_frequency_data, aes(x = claim_frequency)) +\n  geom_histogram(\n    binwidth = 0.1,\n    fill = \"darkorange\",\n    colour = \"white\"\n  ) +\n  coord_cartesian(xlim = c(0, 5)) +\n  scale_x_continuous(\n    breaks = seq(0, 5, by = 0.5)\n  ) +\n  scale_y_continuous(labels = scales::comma) +\n  labs(\n    title = \"Distribution of Claim Frequency\",\n    subtitle = \"Displayed range is limited to 0–5 to show the main concentration of values\",\n    x = \"Claim Frequency\",\n    y = \"Number of Policies\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n\nWe will transform it into categorical variable, similar to loss ratio. \nNo Claim: Claim frequency = 0 \nLow Claim Frequency: Claim frequency \\> 0 & \\<= 1 \nHigh Claim Frequency: Claim frequency \\> 1\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmotor_insurance_final <- motor_insurance_final %>%\n  mutate(\n    claim_frequency_group = case_when(\n      claim_frequency == 0 ~ \"No Claim\",\n      claim_frequency > 0 & claim_frequency <= 1 ~ \"Low Claim Frequency\",\n      claim_frequency > 1 ~ \"High Claim Frequency\"\n    )\n  )\n```\n:::\n\n\n::: panel-tabset\n## Plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-33-1.png){width=672}\n:::\n:::\n\n\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmotor_insurance_final %>%\n  filter(!is.na(claim_frequency_group)) %>%\n  count(claim_frequency_group) %>%\n  mutate(\n    percentage = n / sum(n) * 100,\n    claim_frequency_group = factor(\n      claim_frequency_group,\n      levels = c(\"No Claim\", \"Low Claim Frequency\", \"High Claim Frequency\")\n    ),\n    label = paste0(scales::comma(n), \"\\n(\", round(percentage, 1), \"%)\")\n  ) %>%\n  ggplot(aes(x = claim_frequency_group, y = n)) +\n  geom_col(fill = \"darkorange\", colour = \"white\") +\n  geom_text(\n    aes(label = label),\n    vjust = -0.4,\n    size = 3.5\n  ) +\n  scale_y_continuous(\n    labels = scales::comma,\n    expand = expansion(mult = c(0, 0.25))\n  ) +\n  coord_cartesian(clip = \"off\") +\n  labs(\n    title = \"Distribution of Claim Frequency Groups\",\n    subtitle = \"Claim frequency was grouped to improve interpretability of claim activity\",\n    x = \"Claim Frequency Group\",\n    y = \"Number of Policies\"\n  ) +\n  theme_minimal() +\n  theme(\n    plot.margin = margin(t = 20, r = 10, b = 10, l = 10)\n  )\n```\n:::\n\n:::\n\n::: {.callout-note title=\"Insights\"}\n-   The portfolio is highly concentrated in the **No Claim** group, with **301,814 policies (85.7%)** having no claims.\n\n-   **Low Claim Frequency** accounts for **17,911 policies (5.1%)**, while **High Claim Frequency** accounts for **32,565 policies (9.2%)**.\n\n-   This pattern is expected in insurance portfolios, where most policyholders do not make claims within a given year.\n\n-   The **High Claim Frequency** group is still important as it may contribute more to portfolio volatility and should be explored further in bivariate analysis.\n:::\n\n### 5.2 Claim Severity\n\nWe will only analyse claims only for claims severity because policies with no claims will have `NA` and claims severity is only meaningful when a claim exists\n\n::: panel-tabset\n## Plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-35-1.png){width=672}\n:::\n:::\n\n\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter to policies with claims only\nclaim_severity_data <- motor_insurance_final %>%\n  filter(total_claims > 0, is.finite(claim_severity))\n\n# Summary statistics\nmean_claim_severity <- round(mean(claim_severity_data$claim_severity, na.rm = TRUE), 0)\nmedian_claim_severity <- round(median(claim_severity_data$claim_severity, na.rm = TRUE), 0)\nsd_claim_severity <- round(sd(claim_severity_data$claim_severity, na.rm = TRUE), 0)\n\n# Boxplot\nclaim_severity_box <- ggplot(claim_severity_data, aes(x = claim_severity, y = \"\")) +\n  geom_boxplot(\n    fill = \"grey80\",\n    colour = \"grey30\",\n    outlier.colour = \"grey50\",\n    outlier.alpha = 0.35\n  ) +\n  stat_summary(\n    fun = mean,\n    geom = \"point\",\n    colour = \"black\",\n    size = 3\n  ) +\n  coord_cartesian(xlim = c(0, 5000)) +\n  scale_x_continuous(\n    labels = scales::comma,\n    breaks = seq(0, 5000, by = 1000)\n  ) +\n  labs(\n    title = \"Distribution of Claim Severity\",\n    x = NULL,\n    y = NULL\n  ) +\n  theme_minimal() +\n  theme(\n    axis.text.y = element_blank(),\n    axis.ticks.y = element_blank(),\n    panel.grid.major.y = element_blank()\n  )\n\n# Histogram\nclaim_severity_hist <- ggplot(claim_severity_data, aes(x = claim_severity)) +\n  geom_histogram(\n    binwidth = 250,\n    fill = \"pink\",\n    colour = \"white\"\n  ) +\n  geom_vline(\n    xintercept = median_claim_severity,\n    colour = \"blue\",\n    linetype = \"dashed\",\n    linewidth = 0.8\n  ) +\n  geom_vline(\n    xintercept = mean_claim_severity,\n    colour = \"black\",\n    linetype = \"dashed\",\n    linewidth = 0.8\n  ) +\n  annotate(\n    \"text\",\n    x = median_claim_severity + 140,\n    y = 36000,\n    label = paste0(\"Median = \", scales::comma(median_claim_severity)),\n    colour = \"blue\",\n    size = 3.5,\n    hjust = 0\n  ) +\n  annotate(\n    \"text\",\n    x = mean_claim_severity + 180,\n    y = 44000,\n    label = paste0(\"Mean = \", scales::comma(mean_claim_severity)),\n    colour = \"black\",\n    size = 3.5,\n    hjust = 0\n  ) +\n  annotate(\n    \"text\",\n    x = 3400,\n    y = 44000,\n    label = paste0(\"SD = \", scales::comma(sd_claim_severity)),\n    colour = \"grey30\",\n    size = 3.5\n  ) +\n  coord_cartesian(xlim = c(0, 5000)) +\n  scale_x_continuous(\n    labels = scales::comma,\n    breaks = seq(0, 5000, by = 1000)\n  ) +\n  scale_y_continuous(labels = scales::comma) +\n  labs(\n    subtitle = \"Only policies with claims are included; x-axis is zoomed due to high-severity outliers\",\n    x = \"Claim Severity\",\n    y = \"Number of Policies\"\n  ) +\n  theme_minimal()\n\n# Combine boxplot and histogram\nclaim_severity_box / claim_severity_hist +\n  plot_layout(heights = c(1, 3))\n```\n:::\n\n:::\n\n::: {.callout-note title=\"Insights\"}\n-   The `claim_severity` distribution is **strongly right-skewed** with most claim costs concentrated at the **lower end** of the scale\n-   The **median claim severity is around 498**, while the **mean is higher at around 849** suggesting that a smaller number of expensive claims is pulling the average upward.\n-   The **standard deviation is large at 2,936**, indicating high variation in claim costs.\n-   The boxplot shows many **high-severity outliers**, this means although most claims are relatively low-cost, a small group of severe claims may contribute disproportionately to portfolio volatility.\n:::\n\n# Spearman Correlation\n\n::: panel-tabset\n## Plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-37-1.png){width=960}\n:::\n:::\n\n\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Select numerical variables for Spearman correlation\nspearman_data <- motor_insurance_final %>%\n  select(\n    driver_age,\n    vehicle_age,\n    driving_experience,\n    vehicle_value,\n    total_premium,\n    total_incurred,\n    total_claims,\n    loss_ratio,\n    claim_frequency,\n    claim_severity,\n    underwriting_profit\n  ) %>%\n  mutate(\n    across(everything(), ~ ifelse(is.finite(.), ., NA))\n  )\n\n# Compute Spearman correlation matrix\nspearman_cor_matrix <- cor(\n  spearman_data,\n  use = \"pairwise.complete.obs\",\n  method = \"spearman\"\n)\n\n# Plot Spearman correlation matrix\ncorrplot::corrplot(\n  spearman_cor_matrix,\n  method = \"color\",\n  type = \"upper\",\n  order = \"hclust\",\n  addCoef.col = \"black\",\n  number.cex = 0.65,\n  tl.col = \"black\",\n  tl.srt = 45,\n  tl.cex = 0.8,\n  col = colorRampPalette(c(\"#4D96FF\", \"white\", \"#FF6B6B\"))(200),\n  title = \"Spearman Correlation Matrix of Numerical Variables\",\n  mar = c(0, 0, 2, 0)\n)\n```\n:::\n\n:::\n\n::: {.callout-note title=\"Findings\"}\n-   Spearman correlation results show that most numerical variables have **weak or near-zero relationships** with the key insurance outcomes, suggesting that no single variable strongly explains claim frequency, claim severity or loss ratio on its own.\n\n-   Age-related variables such as `driver_age`, `vehicle_age` and `driving_experience` show **very low correlations** with the outcome variables. This suggests that age may not have a strong direct monotonic relationship with profitability or claims outcomes in this dataset.\n\n-   Stronger patterns are likely to be found through **categorical group comparisons** or segmented analysis instead of correlation alone, since insurance risk may depend on non-linear effects, policy type, bonus score, vehicle characteristics or claim history.\n:::\n\nA separate correlation matrix was also considered for claim policies only, since claim severity is more meaningful when a claim has occurred. This helps reduce the effect of zero-claim policies and provides a clearer view of relationships among claim-related variables.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-39-1.png){width=672}\n:::\n:::\n\n\n::: {.callout-note title=\"Findings\"}\n-   After filtering to policies with claims only, the claim-related variables show stronger relationships. `total_incurred` has a strong positive correlation with `claim_severity` (0.91), which makes sense because severity increases when the incurred claim amount is higher.\n-   `total_claims` and `claim_frequency` also show a strong positive correlation (0.70), suggesting that policies with more claims naturally tend to have higher claim frequency.\n-   Age-related variables such as `driver_age`, `vehicle_age` and `driving_experience` still show near-zero correlations with claim outcomes, suggesting that age-related factors may not have a strong monotonic relationship with claim severity, frequency or loss ratio in this dataset.\n:::\n\n# Bivariate Visual Analysis\n\nThe Spearman correlation analysis showed that most numerical variables had weak or near-zero monotonic relationships with the key insurance outcomes, such as claim frequency, claim severity, loss ratio and underwriting profit. This suggests that the relationships in the dataset may not be strongly linear or direct.\n\nTherefore, the bivariate visual analysis focuses on selected variables that are more meaningful from an insurance and business perspective, such as policy type, bonus score, vehicle characteristics and age-related groups. Instead of using every variable, selected charts are used to check whether clearer patterns appear through categorical group comparisons, segmented distributions or non-linear relationships. This helps keep the analysis focused while also avoiding repetitive charts where the correlation results already suggest limited direct relationship.\n\n## Profitability\n\n### 1. Loss Ratio Group vs Policy Type\n\nThe stacked percentage bar chart is used to compare the relationship between two categorical variables: `policy_type` and `loss_ratio_group`. The x-axis represents the different policy types, while the y-axis shows the percentage of policies within each policy type. Each bar is divided into three profitability groups: `No Loss`, `Profitable / Acceptable`, and `Loss-making`. Using percentages instead of raw counts allows the profitability composition of each policy type to be compared fairly, even though some policy types have many more policies than others. This visualisation helps identify whether certain policy types have a higher proportion of loss-making policies, which may indicate poorer profitability performance.\n\n::: panel-tabset\n## Plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-40-1.png){width=672}\n:::\n:::\n\n\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprofitability_policy <- motor_insurance_final %>%\n  filter(!is.na(loss_ratio_group), !is.na(policy_type)) %>%\n  count(policy_type, loss_ratio_group) %>%\n  group_by(policy_type) %>%\n  mutate(\n    percentage = n / sum(n) * 100,\n    label = ifelse(percentage >= 3, paste0(round(percentage, 1), \"%\"), \"\")\n  ) %>%\n  ungroup() %>%\n  mutate(\n    policy_type = factor(policy_type, levels = c(\"CC\", \"COMP_E\", \"COMP_N\", \"TP\", \"TPG\")),\n    loss_ratio_group = factor(\n      loss_ratio_group,\n      levels = c(\"No Loss\", \"Profitable / Acceptable\", \"Loss-making\")\n    )\n  )\n\nggplot(profitability_policy,\n       aes(x = policy_type, y = percentage, fill = loss_ratio_group)) +\n  geom_col(colour = \"white\", width = 0.8) +\n  geom_text(\n    aes(label = label),\n    position = position_stack(vjust = 0.5),\n    size = 3.2\n  ) +\n  scale_y_continuous(\n    labels = function(x) paste0(x, \"%\")\n  ) +\n  scale_fill_brewer(palette = \"Set2\") +\n  labs(\n    title = \"Loss Ratio Group by Policy Type\",\n    subtitle = \"Shows profitability composition across different policy types\",\n    x = \"Policy Type\",\n    y = \"Percentage of Policies\",\n    fill = \"Loss Ratio Group\"\n  ) +\n  theme_minimal() +\n  theme(\n    legend.position = \"right\"\n  )\n```\n:::\n\n:::\n\n::: {.callout-note title=\"Insights from visuals\"}\n-   Most policies have no loss across all policy types, with TP having the highest “No Loss” proportion at 94.7%, followed by TPG at 91.2% and CC at 90.5%.\n-   COMP_N looks the riskiest, because it has the highest proportion of Loss-making policies at 20.8%, much higher than the other policy types\n-   Profitable / Acceptable policies form a small share overall, but COMP_N has the highest proportion at 8.3%, while COMP_E is next at 4.4%\n:::\n\n#### Statistical Test\n\nSince both `policy_type` and `loss_ratio_group` are categorical variables, a Chi-square test of independence was used to validate whether profitability composition differs across policy types.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show code\"}\nprofitability_table <- motor_insurance_final %>%\n  filter(!is.na(policy_type), !is.na(loss_ratio_group)) %>%\n  count(policy_type, loss_ratio_group) %>%\n  pivot_wider(\n    names_from = loss_ratio_group,\n    values_from = n,\n    values_fill = 0\n  )\n\nprofitability_matrix <- profitability_table %>%\n  column_to_rownames(\"policy_type\") %>%\n  as.matrix()\n\nchisq.test(profitability_matrix)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  profitability_matrix\nX-squared = 7921.4, df = 8, p-value < 2.2e-16\n```\n\n\n:::\n:::\n\n\n::: {.callout-note title=\"Statistical Test Findings\"}\n-   The Chi-square test shows a **statistically significant association** between `policy_type` and `loss_ratio_group` (χ² = 7921.4, df = 8, p \\< 0.001).\n-   Most policy types are dominated by the **No Loss** group, especially `TP` and `TPG`, which have very high proportions of no-loss policies.\n-   `COMP_N` stands out as the riskier policy type, as it has a relatively higher proportion of **Loss-making** policies compared with the other policy types.\n:::\n\n### 2. Underwriting Profit vs Bonus Score\n\nA half-eye plot with embedded boxplot was used to compare `underwriting_profit` across `bonus_score` groups. This plot was chosen because it combines the strengths of both a density plot and a boxplot. The half-eye density shows where underwriting profit values are more concentrated, while the boxplot summarises the median and interquartile range. This makes it useful for comparing the shape, spread, and central tendency of profitability across policyholders with different past claims profiles. The red dashed line at zero represents the break-even point.\n\n::: panel-tabset\n## Plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-43-1.png){width=864}\n:::\n:::\n\n\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nunderwriting_bonus_data <- motor_insurance_final %>%\n  filter(\n    !is.na(bonus_score),\n    is.finite(underwriting_profit),\n    underwriting_profit >= -1000,\n    underwriting_profit <= 1500\n  ) %>%\n  mutate(\n    bonus_score = factor(\n      bonus_score,\n      levels = c(\"Good\", \"Neutral\", \"Bad\")\n    )\n  )\n\n# Median values for annotation\nmedian_bonus <- underwriting_bonus_data %>%\n  group_by(bonus_score) %>%\n  summarise(\n    median_profit = median(underwriting_profit, na.rm = TRUE)\n  )\n\nggplot(\n  underwriting_bonus_data,\n  aes(x = underwriting_profit, y = bonus_score, fill = bonus_score)\n) +\n  ggdist::stat_halfeye(\n    adjust = 0.7,\n    width = 0.6,\n    justification = -0.2,\n    alpha = 0.85,\n    colour = \"grey40\"\n  ) +\n  geom_boxplot(\n    width = 0.12,\n    outlier.shape = NA,\n    fill = \"white\",\n    colour = \"grey30\"\n  ) +\n  geom_vline(\n    xintercept = 0,\n    linetype = \"dashed\",\n    colour = \"red\",\n    linewidth = 0.8\n  ) +\n  geom_text(\n    data = median_bonus,\n    aes(\n      x = median_profit,\n      y = bonus_score,\n      label = paste0(\"Median = \", comma(round(median_profit, 0)))\n    ),\n    inherit.aes = FALSE,\n    nudge_y = 0.28,\n    colour = \"black\",\n    size = 3.3,\n    hjust = 0\n  ) +\n  annotate(\n    \"text\",\n    x = 80,\n    y = 3.35,\n    label = \"Break-even\",\n    colour = \"red\",\n    size = 3.5\n  ) +\n  scale_x_continuous(labels = comma) +\n  scale_fill_manual(\n    values = c(\n      \"Good\" = \"#FF6B6B\",\n      \"Neutral\" = \"#4D96FF\",\n      \"Bad\" = \"#6BCB3D\"\n    )\n  ) +\n  labs(\n    title = \"Underwriting Profit by Bonus Score\",\n    subtitle = \"Half-eye plot with boxplot; range limited for readability\",\n    x = \"Underwriting Profit\",\n    y = \"Bonus Score\"\n  ) +\n  theme_minimal() +\n  theme(\n    legend.position = \"none\"\n  )\n```\n:::\n\n:::\n\n::: {.callout-note title=\"Insights from visuals\"}\n-   Most bonus score groups are concentrated above the break-even line, suggesting that most policies have positive underwriting profit within the displayed range.\n-   The Bad bonus score group has the highest median underwriting profit at 342, compared with Neutral = 246 and Good = 236.\n-   The Bad group also shows wider variation, but this should be interpreted carefully because it has far fewer policies than the Good group\n:::\n\n#### Statistical Test\n\nSince `underwriting_profit` is a numerical variable and `bonus_score` consists of three categorical groups, a **Kruskal-Wallis test** was used to assess whether underwriting profit differs across bonus score groups. This non-parametric test was selected because underwriting profit is skewed and contains outliers.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show code\"}\nunderwriting_bonus_test <- motor_insurance_final %>%\n  filter(\n    !is.na(bonus_score),\n    is.finite(underwriting_profit)\n  )\n\nunderwriting_bonus_test %>%\n  kruskal_test(underwriting_profit ~ bonus_score)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 6\n  .y.                      n statistic    df         p method        \n* <chr>                <int>     <dbl> <int>     <dbl> <chr>         \n1 underwriting_profit 352338      977.     2 6.32e-213 Kruskal-Wallis\n```\n\n\n:::\n:::\n\n\nSince the Kruskal-Wallis test is significant, pairwise Wilcoxon tests were conducted to identify which bonus score groups differ from each other. The Benjamini-Hochberg adjustment was used to control for multiple comparisons.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show code\"}\nunderwriting_bonus_test %>%\n  pairwise_wilcox_test(\n    underwriting_profit ~ bonus_score,\n    p.adjust.method = \"BH\"\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 9\n  .y.     group1 group2     n1     n2 statistic         p     p.adj p.adj.signif\n* <chr>   <chr>  <chr>   <int>  <int>     <dbl>     <dbl>     <dbl> <chr>       \n1 underw… Bad    Good     4693 339836    9.92e8 1.47e-181 4.41e-181 ****        \n2 underw… Bad    Neutr…   4693   7809    2.10e7 7.44e- 42 1.12e- 41 ****        \n3 underw… Good   Neutr… 339836   7809    1.21e9 6.53e- 38 6.53e- 38 ****        \n```\n\n\n:::\n:::\n\n\n\n::: {.callout-note title=\"Statistical Test Findings\"}\n-   The Kruskal-Wallis test shows a statistically significant difference in underwriting_profit across bonus score groups.\n-   Pairwise Wilcoxon tests were conducted to identify which specific groups differed.\n-   All pairwise comparisons were significant after adjustment: Bad vs Good, Bad vs Neutral, and Good vs Neutral all had `p.adj < 0.001`.\n-   This suggests that bonus_score differs significantly with `underwriting profit`.\n:::\n\n### 3. Underwriting Profit vs Business Type\n\nA violin plot with boxplot overlay is chosen because underwriting profit is a numerical profitability measure while business type is categorical. Violin shape can tell us where underwriting profit values are concentrated. The boxplot will show us the median and interquartile range.\n\n::: panel-tabset\n## Plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-47-1.png){width=864}\n:::\n:::\n\n\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nunderwriting_business_data <- motor_insurance_final %>%\n  filter(\n    !is.na(business_type),\n    is.finite(underwriting_profit),\n    underwriting_profit >= -1000,\n    underwriting_profit <= 1500\n  ) %>%\n  mutate(\n    business_type = case_when(\n      business_type == \"NB\" ~ \"New Business\",\n      business_type == \"P\" ~ \"Portfolio\",\n      business_type == \"New Business\" ~ \"New Business\",\n      business_type == \"Portfolio\" ~ \"Portfolio\",\n      TRUE ~ as.character(business_type)\n    ),\n    business_type = factor(\n      business_type,\n      levels = c(\"New Business\", \"Portfolio\")\n    )\n  )\n\nggplot(\n  underwriting_business_data,\n  aes(x = business_type, y = underwriting_profit, fill = business_type)\n) +\n  geom_violin(\n    trim = FALSE,\n    alpha = 0.75,\n    colour = \"grey40\"\n  ) +\n  geom_boxplot(\n    width = 0.12,\n    fill = \"white\",\n    colour = \"grey30\",\n    outlier.shape = NA\n  ) +\n  geom_hline(\n    yintercept = 0,\n    linetype = \"dashed\",\n    colour = \"red\",\n    linewidth = 0.8\n  ) +\n  annotate(\n    \"text\",\n    x = 1.5,\n    y = 120,\n    label = \"Break-even\",\n    colour = \"red\",\n    size = 3.5\n  ) +\n  scale_y_continuous(labels = scales::comma) +\n  scale_fill_manual(\n    values = c(\n      \"New Business\" = \"#4D96FF\",\n      \"Portfolio\" = \"#FF6B6B\"\n    )\n  ) +\n  labs(\n    title = \"Underwriting Profit by Business Type\",\n    subtitle = \"Violin plot with boxplot overlay; range limited for readability\",\n    x = \"Business Type\",\n    y = \"Underwriting Profit\"\n  ) +\n  theme_minimal() +\n  theme(\n    legend.position = \"none\"\n  )\n```\n:::\n\n:::\n\n::: {.callout-note title=\"Insights from visuals\"}\n-   Both New Business and Portfolio are mostly concentrated above the break-even line: many policies generate positive underwriting profit\n-   New Business has more concentration closer to the lower positive profit range, while Portfolio is more concentrated at a slightly higher profit range\n-   Both groups still show negative underwriting profit values, meaning some policies are loss-making, but the main concentration is on the profitable side\n:::\n\n#### Statistical Test\n\nA **Wilcoxon rank-sum test** was used to assess whether underwriting profit differs between New Business and Portfolio policies. This non-parametric test was selected because `underwriting_profit` is skewed and contains outliers.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show code\"}\nunderwriting_business_test <- motor_insurance_final %>%\n  filter(\n    !is.na(business_type),\n    is.finite(underwriting_profit)\n  ) %>%\n  mutate(\n    business_type = case_when(\n      business_type == \"NB\" ~ \"New Business\",\n      business_type == \"P\" ~ \"Portfolio\",\n      business_type == \"New Business\" ~ \"New Business\",\n      business_type == \"Portfolio\" ~ \"Portfolio\",\n      TRUE ~ as.character(business_type)\n    ),\n    business_type = factor(\n      business_type,\n      levels = c(\"New Business\", \"Portfolio\")\n    )\n  )\n\nwilcox.test(\n  underwriting_profit ~ business_type,\n  data = underwriting_business_test\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon rank sum test with continuity correction\n\ndata:  underwriting_profit by business_type\nW = 9369340678, p-value < 2.2e-16\nalternative hypothesis: true location shift is not equal to 0\n```\n\n\n:::\n:::\n\n\n::: {.callout-note title=\"Statistical Test Findings\"}\n- The Wilcoxon rank-sum test shows a **statistically significant difference** in underwriting profit between New Business and Portfolio policies.\n\n- The result is significant with **p < 0.001**, suggesting that underwriting profit differs across the two business types.\n\n- This supports the violin plot finding, where Portfolio policies generally appear to have higher underwriting profit than New Business policies.\n\n- This suggests that existing portfolio policies may be more profitable than newly acquired policies.\n:::\n\n\n### 4. Driver Age vs Loss Ratio Group\n\nA median-IQR error bar plot was used to compare underwriting profit across driver age bands. The point and line show the median underwriting profit, while the vertical error bars represent the interquartile range, or the middle 50% of policies in each age group.\n\n::: panel-tabset\n## Plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-50-1.png){width=864}\n:::\n:::\n\n\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Prepare data\nage_profit_data <- motor_insurance_final %>%\n  filter(\n    !is.na(driver_age),\n    !is.na(underwriting_profit),\n    is.finite(driver_age),\n    is.finite(underwriting_profit)\n  ) %>%\n  mutate(\n    driver_age_band = case_when(\n      driver_age < 30 ~ \"Below 30\",\n      driver_age >= 30 & driver_age < 40 ~ \"30-39\",\n      driver_age >= 40 & driver_age < 50 ~ \"40-49\",\n      driver_age >= 50 & driver_age < 60 ~ \"50-59\",\n      driver_age >= 60 ~ \"60 and above\"\n    ),\n    driver_age_band = factor(\n      driver_age_band,\n      levels = c(\"Below 30\", \"30-39\", \"40-49\", \"50-59\", \"60 and above\")\n    )\n  ) %>%\n  filter(!is.na(driver_age_band))\n\n# Summarise profitability by age band\nage_profit_summary <- age_profit_data %>%\n  group_by(driver_age_band) %>%\n  summarise(\n    n = n(),\n    median_underwriting_profit = median(underwriting_profit, na.rm = TRUE),\n    q1 = quantile(underwriting_profit, 0.25, na.rm = TRUE),\n    q3 = quantile(underwriting_profit, 0.75, na.rm = TRUE),\n    .groups = \"drop\"\n  ) %>%\n  mutate(\n    label = paste0(\"n = \", scales::comma(n))\n  )\n\n# Plot median underwriting profit with IQR\nage_profit_summary %>%\n  ggplot(aes(\n    x = driver_age_band,\n    y = median_underwriting_profit,\n    group = 1\n  )) +\n  geom_errorbar(\n    aes(ymin = q1, ymax = q3),\n    width = 0.15,\n    linewidth = 0.8\n  ) +\n  geom_line(\n    linewidth = 0.9,\n    alpha = 0.8\n  ) +\n  geom_point(\n    size = 3\n  ) +\n  geom_text(\n    aes(label = label),\n    position = position_nudge(x = 0.08, y = 8),\n    hjust = 0,\n    size = 3.3\n  ) +\n  geom_hline(\n    yintercept = 0,\n    linetype = \"dashed\",\n    linewidth = 0.7\n  ) +\n  scale_y_continuous(labels = scales::comma) +\n  labs(\n    title = \"Median Underwriting Profit by Driver Age Band\",\n    subtitle = \"Shows typical profitability and interquartile range across driver age groups\",\n    x = \"Driver Age Band\",\n    y = \"Median Underwriting Profit\"\n  ) +\n  theme_minimal()\n```\n:::\n\n:::\n\n::: {.callout-note title=\"Insights from Visuals\"}\n-   Median underwriting profit is **positive across all driver age bands**, suggesting that each age group is generally profitable at the median level.\n\n-   The **Below 30** group has the highest median underwriting profit, but it also has the smallest sample size compared with the other age bands. Hence, this difference should be interpreted carefully.\n\n-   For the other age bands, median underwriting profit is fairly similar, mostly around the low-to-mid 200 range. This means that driver age does not appear to be a strong standalone factor in explaining underwriting profitability as what we concluded in the correlation plot\n:::\n\n#### Statistical Test\n\nSince `underwriting_profit` is a numerical variable and `driver_age_band` consists of five categorical groups, a **Kruskal-Wallis test** was used to assess whether underwriting profit differs across driver age bands. This non-parametric test was selected because underwriting profit is skewed and contains extreme values.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show code\"}\nage_profit_test_data <- motor_insurance_final %>%\n  filter(\n    is.finite(driver_age),\n    is.finite(underwriting_profit)\n  ) %>%\n  mutate(\n    driver_age_band = case_when(\n      driver_age < 30 ~ \"Below 30\",\n      driver_age >= 30 & driver_age < 40 ~ \"30-39\",\n      driver_age >= 40 & driver_age < 50 ~ \"40-49\",\n      driver_age >= 50 & driver_age < 60 ~ \"50-59\",\n      driver_age >= 60 ~ \"60 and above\"\n    ),\n    driver_age_band = factor(\n      driver_age_band,\n      levels = c(\"Below 30\", \"30-39\", \"40-49\", \"50-59\", \"60 and above\")\n    )\n  ) %>%\n  filter(!is.na(driver_age_band))\n\nage_profit_test_data %>%\n  kruskal_test(underwriting_profit ~ driver_age_band)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 6\n  .y.                      n statistic    df         p method        \n* <chr>                <int>     <dbl> <int>     <dbl> <chr>         \n1 underwriting_profit 352338      962.     4 7.70e-207 Kruskal-Wallis\n```\n\n\n:::\n:::\n\n\nSince the Kruskal-Wallis test is significant, pairwise Wilcoxon tests were conducted to identify which age bands differ from each other. The Benjamini-Hochberg adjustment was used to control for multiple comparisons.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show code\"}\nage_profit_test_data %>%\n  pairwise_wilcox_test(\n    underwriting_profit ~ driver_age_band,\n    p.adjust.method = \"BH\"\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 9\n   .y.      group1 group2    n1    n2 statistic         p     p.adj p.adj.signif\n * <chr>    <chr>  <chr>  <int> <int>     <dbl>     <dbl>     <dbl> <chr>       \n 1 underwr… Below… 30-39   9521 82876    4.63e8 6.51e-168 6.51e-167 ****        \n 2 underwr… Below… 40-49   9521 96496    5.36e8 2.58e-161 1.29e-160 ****        \n 3 underwr… Below… 50-59   9521 84802    4.59e8 1.65e-105 4.12e-105 ****        \n 4 underwr… Below… 60 an…  9521 78643    4.35e8 4.69e-145 1.56e-144 ****        \n 5 underwr… 30-39  40-49  82876 96496    3.98e9 1.2 e-  1 1.2 e-  1 ns          \n 6 underwr… 30-39  50-59  82876 84802    3.37e9 1.22e- 46 2.44e- 46 ****        \n 7 underwr… 30-39  60 an… 82876 78643    3.21e9 1.37e-  8 1.71e-  8 ****        \n 8 underwr… 40-49  50-59  96496 84802    3.94e9 2.20e- 40 3.67e- 40 ****        \n 9 underwr… 40-49  60 an… 96496 78643    3.75e9 1.12e-  5 1.24e-  5 ****        \n10 underwr… 50-59  60 an… 84802 78643    3.42e9 5.11e- 18 7.30e- 18 ****        \n```\n\n\n:::\n:::\n\n\n::: {.callout-note title=\"Statistical Test Findings\"}\n-   The Kruskal-Wallis test shows a **statistically significant difference** in underwriting profit across driver age bands (χ² = 961.54, df = 4, p \\< 0.001). This suggests that underwriting profit is not distributed exactly the same across all age groups.\n\n-   The Pairwise Wilcoxon test with Bonferroni adjustment shows that most age band pairs are significantly different. However, **30–39 vs 40–49** is not significant (p = 1.000), suggesting that these two age groups have very similar underwriting profit distributions.\n\n-   This is generally consistent with the visual analysis. The chart shows that underwriting profit is positive across all age bands, with the **Below 30** group having a higher median. However, most older age bands look fairly close visually, so driver age may have a statistically significant but not strongly relationship with underwriting profit.\n:::\n\n### 5. Average Loss Ratio vs Year\n\n::: panel-tabset\n## Plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-54-1.gif)\n:::\n:::\n\n\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nyearly_loss_ratio <- motor_insurance_final %>%\n  filter(is.finite(loss_ratio)) %>%\n  mutate(year_num = as.numeric(as.character(year))) %>%\n  group_by(year_num) %>%\n  summarise(\n    avg_loss_ratio = mean(loss_ratio, na.rm = TRUE),\n    .groups = \"drop\"\n  )\n\np_temporal_loss <- ggplot(\n  yearly_loss_ratio,\n  aes(x = year_num, y = avg_loss_ratio)\n) +\n  geom_hline(\n    yintercept = 1,\n    linetype = \"dashed\",\n    colour = \"red\",\n    linewidth = 0.8\n  ) +\n  geom_line(\n    colour = \"mediumpurple\",\n    linewidth = 1.2\n  ) +\n  geom_point(\n    colour = \"mediumpurple\",\n    size = 3\n  ) +\n  geom_text(\n    aes(label = round(avg_loss_ratio, 2)),\n    vjust = -0.8,\n    size = 4,\n    colour = \"mediumpurple4\"\n  ) +\n  annotate(\n    \"text\",\n    x = max(yearly_loss_ratio$year_num),\n    y = 1.02,\n    label = \"Break-even\",\n    colour = \"red\",\n    hjust = 1,\n    size = 4\n  ) +\n  scale_x_continuous(\n    breaks = yearly_loss_ratio$year_num\n  ) +\n  scale_y_continuous(\n    limits = c(0.6, 1.05),\n    labels = label_number(accuracy = 0.01)\n  ) +\n  labs(\n    title = \"Temporal Trend of Average Loss Ratio\",\n    subtitle = \"Average loss ratio by year\",\n    x = \"Year\",\n    y = \"Average Loss Ratio\"\n  ) +\n  theme_minimal() +\n  transition_reveal(year_num)\n\nanimate(\n  p_temporal_loss,\n  nframes = 80,\n  fps = 10,\n  width = 800,\n  height = 500,\n  end_pause = 20,\n  renderer = gifski_renderer()\n)\n```\n:::\n\n:::\n\n::: {.callout-note title=\"Insights from Visuals\"}\n-   The average loss ratio increased from **0.67 in 2022** to **0.73 in 2023**, and further to **0.87 in 2024**.\n\n-   Although the average loss ratio remains below the **break-even point of 1.00** across all three years, the upward trend suggests that portfolio profitability is **weakening over time**.\n\n-   This means that a larger share of premium collected is being used to cover incurred claims each year.\n\n-   If this trend continues, the portfolio may face greater **profitability pressure**, as the average loss ratio is moving closer to the loss-making threshold.\n:::\n\n#### Statistical Test\n\nSince `loss_ratio` is a numerical variable and `year` consists of three groups, a **Kruskal-Wallis test** was used to assess whether loss ratio differs across years. This non-parametric test was selected because loss ratio is highly skewed and contains extreme values.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show code\"}\nloss_ratio_year_test <- motor_insurance_final %>%\n  filter(\n    !is.na(year),\n    is.finite(loss_ratio)\n  )\n\nloss_ratio_year_test %>%\n  kruskal_test(loss_ratio ~ year)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 6\n  .y.             n statistic    df        p method        \n* <chr>       <int>     <dbl> <int>    <dbl> <chr>         \n1 loss_ratio 352289      196.     2 2.69e-43 Kruskal-Wallis\n```\n\n\n:::\n:::\n\n\n Kruskal-Wallis test is significant, pairwise Wilcoxon tests were conducted to identify which year pairs differ from each other. The Benjamini-Hochberg adjustment was used to control for multiple comparisons.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show code\"}\nloss_ratio_year_test %>%\n  pairwise_wilcox_test(\n    loss_ratio ~ year,\n    p.adjust.method = \"BH\"\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 9\n  .y.       group1 group2     n1     n2 statistic        p    p.adj p.adj.signif\n* <chr>     <chr>  <chr>   <int>  <int>     <dbl>    <dbl>    <dbl> <chr>       \n1 loss_rat… 2022   2023    66889 118264    3.92e9 9.33e-10 9.33e-10 ****        \n2 loss_rat… 2022   2024    66889 167136    5.48e9 2.61e-40 7.83e-40 ****        \n3 loss_rat… 2023   2024   118264 167136    9.78e9 3.83e-17 5.74e-17 ****        \n```\n\n\n:::\n:::\n\n\n\n::: {.callout-note title=\"Statistical Test Findings\"}\n-   The pairwise Wilcoxon test shows that `loss_ratio` differs significantly across all year pairs.\n\n-   **2022 vs 2023** is statistically significant after adjustment, with `p.adj < 0.001`.\n\n-   **2022 vs 2024** and **2023 vs 2024** are also statistically significant after adjustment, with `p.adj < 0.001`.\n\n-   This confirms that the increase in average loss ratio observed in the temporal line chart is statistically supported, suggesting that portfolio profitability changed significantly across years.\n:::\n\n## Volatility\n\n### 1. Claim Severity vs Municipality Type\n\n::: panel-tabset\n## Plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-58-1.png){width=960}\n:::\n:::\n\n\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nseverity_muni_data <- motor_insurance_final %>%\n  filter(\n    total_claims > 0,\n    !is.na(municipality_type),\n    !is.na(claim_severity),\n    is.finite(claim_severity),\n    claim_severity > 0\n  )\n\nseverity_zoom_limit <- quantile(\n  severity_muni_data$claim_severity,\n  0.95,\n  na.rm = TRUE\n)\n\nseverity_muni_data %>%\n  filter(claim_severity <= severity_zoom_limit) %>%\n  ggplot(aes(\n    x = claim_severity,\n    fill = municipality_type\n  )) +\n  geom_density(\n    alpha = 0.6\n  ) +\n  facet_wrap(~ municipality_type, ncol = 1) +\n  scale_x_continuous(labels = scales::comma) +\n  labs(\n    title = \"Claim Severity Distribution by Municipality Type\",\n    subtitle = \"Zoomed-in view up to the 95th percentile of claim severity\",\n    x = \"Claim Severity\",\n    y = \"Density\"\n  ) +\n  theme_minimal() +\n  theme(\n    legend.position = \"none\"\n  )\n```\n:::\n\n:::\n\n::: {.callout-note title=\"Insights from Visuals\"}\n-   Claim severity shows a broadly similar distribution across **Coastal**, **Inland** and **Islands**, with most claims concentrated below around **1,200** after zooming into the 95th percentile.\n\n-   All three municipality types show a right-skewed pattern, meaning most claims are relatively low in severity, while a smaller number of claims have higher severity.\n\n-   The **Islands** group appears to have a slightly stronger concentration around the higher-severity range near **1,000–1,200**, while **Coastal** and **Inland** show more spread across both lower and mid-severity values. However, the overall patterns are still quite similar, so municipality type may not be a very strong differentiator of claim severity.\n:::\n\n#### Statistical Test\n\nSince `claim_severity` is a numerical variable and `municipality_type` consists of three categorical groups, a **Kruskal-Wallis test** was used to assess whether claim severity differs across municipality types. This non-parametric test was selected because claim severity is highly skewed and contains high-severity outliers. Only policies with claims were included because claim severity is only meaningful when a claim exists.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show code\"}\nseverity_muni_test_data <- motor_insurance_final %>%\n  filter(\n    total_claims > 0,\n    !is.na(municipality_type),\n    is.finite(claim_severity),\n    claim_severity > 0\n  )\n\nseverity_muni_test_data %>%\n  kruskal_test(claim_severity ~ municipality_type)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 6\n  .y.                n statistic    df        p method        \n* <chr>          <int>     <dbl> <int>    <dbl> <chr>         \n1 claim_severity 41978      50.3     2 1.21e-11 Kruskal-Wallis\n```\n\n\n:::\n:::\n\n\nSince the Kruskal-Wallis test is significant, pairwise Wilcoxon tests were conducted. The Benjamini-Hochberg adjustment was used to control for multiple comparisons.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show code\"}\nseverity_muni_test_data %>%\n  pairwise_wilcox_test(\n    claim_severity ~ municipality_type,\n    p.adjust.method = \"BH\"\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 9\n  .y.          group1 group2    n1    n2 statistic        p   p.adj p.adj.signif\n* <chr>        <chr>  <chr>  <int> <int>     <dbl>    <dbl>   <dbl> <chr>       \n1 claim_sever… Coast… Inland 11288 28282    1.64e8 2.53e- 5 3.8 e-5 ****        \n2 claim_sever… Coast… Islan… 11288  2408    1.29e7 1.29e- 4 1.29e-4 ***         \n3 claim_sever… Inland Islan… 28282  2408    3.14e7 3.56e-10 1.07e-9 ****        \n```\n\n\n:::\n:::\n\n\n::: {.callout-note title=\"Statistical Test Findings\"}\n-   The Kruskal-Wallis test shows a **statistically significant difference** in claim severity across municipality types (χ² = 50.269, df = 2, p \\< 0.001). This suggests that claim severity is not distributed exactly the same across Coastal, Inland and Islands policies.\n\n-   The Pairwise Wilcoxon tests with Bonferroni adjustment show that **all municipality type pairs are significantly different**: Inland vs Coastal (p \\< 0.001), Islands vs Coastal (p \\< 0.001), and Islands vs Inland (p \\< 0.001).\n\n-   This supports the visual analysis because the claim severity patterns are not exactly the same across municipality types. However, the differences are not very obvious from the chart, so municipality type may have some relationship with claim severity, but it does not appear to be a strong standalone factor.\n:::\n\n### 2. Claim Frequency vs Vehicle Value Band\n\n::: panel-tabset\n## Plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-62-1.png){width=864}\n:::\n:::\n\n\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Prepare data\nvehicle_claim_freq_heatmap_data <- motor_insurance_final %>%\n  mutate(\n    claim_frequency_group = case_when(\n      claim_frequency == 0 ~ \"No Claim\",\n      claim_frequency > 0 & claim_frequency <= 1 ~ \"Low Claim Frequency\",\n      claim_frequency > 1 ~ \"High Claim Frequency\"\n    )\n  ) %>%\n  filter(\n    !is.na(vehicle_value),\n    !is.na(claim_frequency_group),\n    is.finite(vehicle_value),\n    vehicle_value > 0\n  ) %>%\n  mutate(\n    vehicle_value_band = ntile(vehicle_value, 4),\n    vehicle_value_band = factor(\n      vehicle_value_band,\n      levels = 1:4,\n      labels = c(\"Low\", \"Lower-Mid\", \"Upper-Mid\", \"High\")\n    ),\n    claim_frequency_group = factor(\n      claim_frequency_group,\n      levels = c(\"No Claim\", \"Low Claim Frequency\", \"High Claim Frequency\")\n    )\n  ) %>%\n  count(vehicle_value_band, claim_frequency_group) %>%\n  group_by(vehicle_value_band) %>%\n  mutate(\n    percentage = n / sum(n),\n    label = paste0(scales::comma(n), \"\\n\", scales::percent(percentage, accuracy = 0.1))\n  ) %>%\n  ungroup()\n\n# Heatmap\nvehicle_claim_freq_heatmap_data %>%\n  ggplot(aes(\n    x = vehicle_value_band,\n    y = claim_frequency_group,\n    fill = percentage\n  )) +\n  geom_tile(colour = \"white\", linewidth = 1) +\n  geom_text(\n    aes(label = label),\n    size = 3.5,\n    colour = \"black\"\n  ) +\n  scale_fill_gradientn(\n    colours = c(\"#d73027\", \"#fee08b\", \"#1a9850\"),\n    labels = scales::percent\n  ) +\n  labs(\n    title = \"Claim Frequency Group by Vehicle Value Band\",\n    subtitle = \"Heatmap showing claim frequency composition within each vehicle value band\",\n    x = \"Vehicle Value Band\",\n    y = \"Claim Frequency Group\",\n    fill = \"Percentage of Policies\"\n  ) +\n  theme_minimal()\n```\n:::\n\n:::\n\n::: {.callout-note title=\"Insights from Visuals\"}\n-   Across all vehicle value bands, the majority of policies fall under the **No Claim** group. However, this proportion gradually declines as vehicle value increases, from **88.8%** in the Low band to **82.4%** in the High band.\n\n-   The proportion of **High Claim Frequency** policies increases steadily across vehicle value bands, rising from **7.3%** in the Low band to **11.5%** in the High band. This suggests that higher-value vehicles are associated with a greater concentration of more frequent claims.\n\n-   A similar upward pattern is seen for **Low Claim Frequency** policies, which increase from **3.9%** to **6.1%** across the bands. Overall, this indicates that higher vehicle value bands tend to have slightly less stable claim experience compared with lower-value bands.\n:::\n\n#### Statistical Test\n\nSince both `vehicle_value_band` and `claim_frequency_group` are categorical variables, a **Chi-square test of independence** was used to assess whether claim frequency composition differs across vehicle value bands.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show code\"}\nvehicle_claim_freq_test_data <- motor_insurance_final %>%\n  mutate(\n    claim_frequency_group = case_when(\n      claim_frequency == 0 ~ \"No Claim\",\n      claim_frequency > 0 & claim_frequency <= 1 ~ \"Low Claim Frequency\",\n      claim_frequency > 1 ~ \"High Claim Frequency\"\n    )\n  ) %>%\n  filter(\n    is.finite(vehicle_value),\n    vehicle_value > 0,\n    !is.na(claim_frequency_group)\n  ) %>%\n  mutate(\n    vehicle_value_band = ntile(vehicle_value, 4),\n    vehicle_value_band = factor(\n      vehicle_value_band,\n      levels = 1:4,\n      labels = c(\"Low\", \"Lower-Mid\", \"Upper-Mid\", \"High\")\n    ),\n    claim_frequency_group = factor(\n      claim_frequency_group,\n      levels = c(\"No Claim\", \"Low Claim Frequency\", \"High Claim Frequency\")\n    )\n  )\n\nvehicle_claim_freq_table <- vehicle_claim_freq_test_data %>%\n  count(vehicle_value_band, claim_frequency_group) %>%\n  pivot_wider(\n    names_from = claim_frequency_group,\n    values_from = n,\n    values_fill = 0\n  )\n\nvehicle_claim_freq_matrix <- vehicle_claim_freq_table %>%\n  column_to_rownames(\"vehicle_value_band\") %>%\n  as.matrix()\n\nchisq.test(vehicle_claim_freq_matrix)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  vehicle_claim_freq_matrix\nX-squared = 1577.9, df = 6, p-value < 2.2e-16\n```\n\n\n:::\n:::\n\n\n::: {.callout-note title=\"Statistical Test Findings\"}\n-   The Chi-square test shows a **statistically significant association** between `vehicle_value_band` and `claim_frequency_group` (χ² = 1577.9, df = 6, p \\< 0.001). Claim frequency group is not the same across vehicle value bands.\n\n-   This supports the heatmap, where the proportion of **No Claim** policies decreases as vehicle value increases, while both **Low Claim Frequency** and **High Claim Frequency** policies increase.\n\n-   Higher-value vehicles seem to have slightly more claim activity compared with lower-value vehicles. However, most policies still have no claims across all vehicle value bands, so vehicle value is related to claim frequency, but it is not the only factor explaining claims.\n:::\n\n### 3. Claim Frequency Group vs Circulation Area\n\n::: panel-tabset\n## Plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-65-1.png){width=864}\n:::\n:::\n\n\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Prepare data\ncirculation_claim_freq_bubble <- motor_insurance_final %>%\n  mutate(\n    claim_frequency_group = case_when(\n      claim_frequency == 0 ~ \"No Claim\",\n      claim_frequency > 0 & claim_frequency <= 1 ~ \"Low Claim Frequency\",\n      claim_frequency > 1 ~ \"High Claim Frequency\"\n    )\n  ) %>%\n  filter(\n    !is.na(circulation_area),\n    !is.na(claim_frequency_group)\n  ) %>%\n  mutate(\n    circulation_area = factor(\n      circulation_area,\n      levels = c(\"Urban\", \"Rural\")\n    ),\n    claim_frequency_group = factor(\n      claim_frequency_group,\n      levels = c(\"No Claim\", \"Low Claim Frequency\", \"High Claim Frequency\")\n    )\n  ) %>%\n  count(circulation_area, claim_frequency_group, name = \"n\") %>%\n  group_by(circulation_area) %>%\n  mutate(\n    percentage = n / sum(n),\n    label = paste0(scales::comma(n), \"\\n\", scales::percent(percentage, accuracy = 0.1))\n  ) %>%\n  ungroup()\n\n# Bubble matrix plot\ncirculation_claim_freq_bubble %>%\n  ggplot(aes(\n    x = circulation_area,\n    y = claim_frequency_group\n  )) +\n  geom_point(\n    aes(size = percentage, fill = claim_frequency_group),\n    shape = 21,\n    colour = \"grey35\",\n    alpha = 0.9\n  ) +\n  geom_text(\n    aes(label = label),\n    size = 3.3,\n    colour = \"black\"\n  ) +\n  scale_size_area(\n    max_size = 35,\n    labels = scales::percent,\n    name = \"Percentage of Policies\"\n  ) +\n  scale_fill_manual(\n    values = c(\n      \"No Claim\" = \"#FF8A80\",\n      \"Low Claim Frequency\" = \"#4FC3F7\",\n      \"High Claim Frequency\" = \"#81C784\"\n    ),\n    name = \"Claim Frequency Group\"\n  ) +\n  guides(\n    fill = guide_legend(\n      order = 1,\n      override.aes = list(size = 6, alpha = 1)\n    ),\n    size = guide_legend(order = 2)\n  ) +\n  labs(\n    title = \"Claim Frequency Group by Circulation Area\",\n    subtitle = \"Bubble matrix showing claim frequency within Urban and Rural policies\",\n    x = \"Circulation Area\",\n    y = \"Claim Frequency Group\"\n  ) +\n  theme_minimal() +\n  theme(\n    panel.grid.major = element_line(colour = \"grey90\"),\n    legend.position = \"right\",\n    legend.box = \"vertical\",\n    legend.spacing.y = unit(0.6, \"cm\"),\n    legend.margin = margin(t = 8, r = 10, b = 8, l = 12),\n    legend.title = element_text(face = \"bold\"),\n    legend.text = element_text(size = 10)\n  )\n```\n:::\n\n:::\n\n::: {.callout-note title=\"Insights from Visuals\"}\n-   Both **Urban** and **Rural** policies are mainly concentrated in the **No Claim** group which could mean that most policies did not record claims regardless of circulation area\n\n-   **Urban** policies show a slightly higher share of **High Claim Frequency** policies at **9.9%**, compared with **8.5%** for Rural policies\n\n-   **Rural** policies have a slightly higher **No Claim** proportion at **86.6%**, compared with **84.9%** for Urban policies. This suggests that Urban policies may have slightly more claim activity, but the overall difference is not very large visually.\n:::\n\n#### Statistical Test\n\nSince both `claim_frequency_group` and `circulation_area` are categorical variables, a **Chi-square test of independence** was used to assess whether claim frequency composition differs between Urban and Rural policies.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show code\"}\ncirculation_claim_freq_test_data <- motor_insurance_final %>%\n  mutate(\n    claim_frequency_group = case_when(\n      claim_frequency == 0 ~ \"No Claim\",\n      claim_frequency > 0 & claim_frequency <= 1 ~ \"Low Claim Frequency\",\n      claim_frequency > 1 ~ \"High Claim Frequency\",\n    )\n  ) %>%\n  filter(\n    !is.na(circulation_area),\n    !is.na(claim_frequency_group)\n  ) %>%\n  mutate(\n    claim_frequency_group = factor(\n      claim_frequency_group,\n      levels = c(\"No Claim\", \"Low Claim Frequency\", \"High Claim Frequency\")\n    )\n  )\n\ncirculation_claim_freq_table <- circulation_claim_freq_test_data %>%\n  count(circulation_area, claim_frequency_group) %>%\n  pivot_wider(\n    names_from = claim_frequency_group,\n    values_from = n,\n    values_fill = 0\n  )\n\ncirculation_claim_freq_matrix <- circulation_claim_freq_table %>%\n  column_to_rownames(\"circulation_area\") %>%\n  as.matrix()\n\nchisq.test(circulation_claim_freq_matrix)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  circulation_claim_freq_matrix\nX-squared = 233.44, df = 2, p-value < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n::: {.callout-note title=\"Statistical Test Findings\"}\n-   The Chi-square test shows a **statistically significant association** between `circulation_area` and `claim_frequency_group` (χ² = 233.44, df = 2, p \\< 0.001). This suggests that claim frequency group is not distributed exactly the same between Urban and Rural policies.\n\n-   This supports the visual analysis, where **Urban** policies have a slightly higher proportion of **High Claim Frequency** policies, while **Rural** policies have a slightly higher proportion of **No Claim** policies.\n\n-   Urban policies appear to have slightly more claim activity than Rural policies. However, most policies in both groups still fall under the **No Claim** group, so the difference is statistically significant but not very large visually.\n:::\n\n### 4. Claim Severity vs Driving Experience Group\n\n::: panel-tabset\n## Plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-Home_Ex01_files/figure-html/unnamed-chunk-68-1.png){width=864}\n:::\n:::\n\n\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Prepare data: only policies with claims\nseverity_exp_ridge <- motor_insurance_final %>%\n  filter(\n    total_claims > 0,\n    is.finite(driving_experience),\n    is.finite(claim_severity),\n    driving_experience >= 0,\n    driving_experience <= 70,\n    claim_severity >= 0,\n    claim_severity <= 5000\n  ) %>%\n  mutate(\n    driving_experience_group = cut(\n      driving_experience,\n      breaks = seq(0, 70, by = 10),\n      include.lowest = TRUE,\n      right = FALSE\n    )\n  ) %>%\n  filter(!is.na(driving_experience_group))\n\n# Ridgeline density plot\nggplot(\n  severity_exp_ridge,\n  aes(\n    x = claim_severity,\n    y = driving_experience_group,\n    fill = driving_experience_group\n  )\n) +\n  ggridges::geom_density_ridges(\n    scale = 1.4,\n    rel_min_height = 0.01,\n    colour = \"white\",\n    linewidth = 0.35,\n    alpha = 0.85\n  ) +\n  scale_x_continuous(\n    labels = scales::comma,\n    breaks = seq(0, 5000, by = 1000)\n  ) +\n  scale_fill_brewer(palette = \"Set2\") +\n  labs(\n    title = \"Claim Severity Distribution by Driving Experience Group\",\n    subtitle = \"Only policies with claims are included; claim severity is capped at 5,000 for readability\",\n    x = \"Claim Severity\",\n    y = \"Driving Experience Group\"\n  ) +\n  theme_minimal() +\n  theme(\n    legend.position = \"none\"\n  )\n\n# Spearman correlation test using original continuous variables\nseverity_exp_test <- motor_insurance_final %>%\n  filter(\n    total_claims > 0,\n    is.finite(driving_experience),\n    is.finite(claim_severity)\n  )\n\nseverity_exp_test %>%\n  cor_test(\n    driving_experience,\n    claim_severity,\n    method = \"spearman\"\n  )\n```\n:::\n\n:::\n\n::: {.callout-note title=\"Insights from Visuals\"}\n-   Claim severity is **right-skewed across all driving experience groups**, with most claims concentrated at the lower severity range.\n\n-   The distribution shapes are broadly similar across experience groups, suggesting that driving experience may not be a strong standalone factor in explaining claim severity.\n\n-   Some groups, especially the **30–40** and **50–60** experience groups, show longer right tails, indicating occasional high-severity claims.\n\n-   Since the visual differences are not very strong, a **Spearman correlation test** should be used to statistically validate whether driving experience is associated with claim severity.\n:::\n\n#### Statistical Test\n\nSince `claim_severity` is a numerical variable and `driving_experience_group` consists of several categorical groups, a **Kruskal-Wallis test** was used to assess whether claim severity differs across driving experience groups. This non-parametric test was selected because claim severity is highly skewed and contains high-severity outliers.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show code\"}\nseverity_exp_ridge %>%\n  kruskal_test(claim_severity ~ driving_experience_group)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 6\n  .y.                n statistic    df        p method        \n* <chr>          <int>     <dbl> <int>    <dbl> <chr>         \n1 claim_severity 49685      96.7     6 1.23e-18 Kruskal-Wallis\n```\n\n\n:::\n:::\n\n\n::: {.callout-note title=\"Statistical Test Findings\"}\n-   The Kruskal-Wallis test shows a **statistically significant difference** in `claim_severity` across driving experience groups. The result is significant with **H(6) = 96.68, p \\< 0.001**.\n\n-   At least one driving experience group has a different claim severity distribution.\n\n-   Since the ridgeline plot shows broadly similar shapes across groups, the difference appears statistically significant but not very visually large. This may be influenced by the large number of claim records used in the test.\n:::\n\n# Summary and Recommendations\n\n## Summary\n\nThis study applied visual analytics and statistical validation to explore profitability and volatility in a Spanish motor insurance portfolio. Overall, the portfolio remains profitable, with average loss ratio below the break-even point of 1.00. However, profitability is weakening over time, as average loss ratio increased from **0.67 in 2022** to **0.87 in 2024**. Claim volatility is mainly driven by claim severity, where most claims are low-cost but a small number of high-severity claims pull the mean upward.\n\n## Key Findings\n\n-   **Policy type is strongly associated with profitability.** COMP_N has the highest loss-making share at **20.8%**, while TP and TPG perform well with **94.7%** and **91.2%** no-loss policies respectively. The Chi-square test confirms a significant association between `policy_type` and `loss_ratio_group` (**χ² = 7921.4, p \\< 0.001**).\n\n-   **Profitability weakened over time.** Average loss ratio increased from **0.67 in 2022** to **0.87 in 2024**. Kruskal-Wallis and pairwise Wilcoxon tests show that loss ratio differs significantly across all year pairs (**p \\< 0.001**).\n\n-   **Business type matters.** Portfolio policies show higher underwriting profit than New Business policies, and the Wilcoxon test confirms a significant difference (**p \\< 0.001**). This suggests that existing policies may be more profitable than newly acquired ones.\n\n-   **Bonus score shows a counterintuitive pattern.** Underwriting profit differs significantly across bonus score groups (**H(2) = 977.21, p \\< 0.001**). The Bad group has the highest median underwriting profit, but this should be interpreted carefully because it is a small group.\n\n-   **Claim severity is the main volatility concern.** Claim severity is strongly right-skewed, with median severity around **498** and mean severity around **849**. This suggests that a small number of expensive claims may contribute disproportionately to volatility.\n\n-   **Continuous variables are weaker predictors.** Driver age, vehicle age, driving experience, and vehicle value show weak relationships with key outcomes, suggesting that categorical segmentation gives clearer insights than continuous variables alone.\n\n## Recommendations for Future Research\n\n-   Investigate the increase in loss ratio from 2022 to 2024 to determine whether it is caused by claim inflation, pricing gaps, portfolio mix changes, or external factors.\n\n-   Review COMP_N policies to understand whether the higher loss-making share is due to pricing, claim severity, coverage structure, or customer risk profile.\n\n-   Study the strong performance of TP and TPG policies to assess whether these segments can be grown sustainably.\n\n-   Investigate the Bad bonus score anomaly to determine whether the higher median profit is due to pricing strategy, coverage mix, or small-group effects.\n\n-   Include external variables such as repair cost trends, inflation, accident rates, weather, and traffic conditions to better explain profitability and volatility patterns.\n\n-   Use more granular claim-level data, such as claim type, cause of accident, repair category, and settlement status, to better understand high-severity claims.\n\n## Overall Conclusion\n\nOverall, profitability and volatility in this portfolio are not driven by one single factor. Policy type, business type, bonus score, and year show significant relationships with profitability, while claim severity remains the key source of volatility. Although the portfolio is still profitable, the rising loss ratio suggests emerging profitability pressure that should be monitored and investigated further.\n\n# References\n\nSociety of Actuaries. (n.d.). Actuarial glossary. https://www.soa.org/globalassets/assets/files/edu/actuarial-glossary.pdf\n",
    "supporting": [
      "Take-Home_Ex01_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}